### ISSUE TITLE
`:helptags` fails sometimes

### ISSUE THREAD

**Issue by gmarik** [VundleVim/Vundle.vim#112]
- when `wildignore` [includes `doc/*` for example](https://github.com/gmarik/vundle/blob/43080a1e5cf789d311b30a9b7c7497e70758da71/test/vimrc#L61-63)
- also `Helptags` lies about success as it always returns `updated` ignoring actual result of `:helptags` per bundle

**Comment by telemenar** [comment]
I think I'm seeing this cause :helptags to fail on my mac. 
```
let doc_path = resolve(a:rtp . '/doc/')
```
Is resolving away the trailing '/'

And
```
:helptags ~/.vim/bundle/vundle/doc
```
fails while
```
:helptags ~/.vim/bundle/vundle/doc/
```
succedes.
