### ISSUE TITLE
Vundle installed colorschemes

### ISSUE THREAD

**Issue by MortalCatalyst** [VundleVim/Vundle.vim#119]
When I install color schemes via vundle they aren't usable or recognised by vim.

so 
colorscheme solarized or railscasts or desert-warm all haven't been recognised.

Does the path for vim recognise that the colrscheme has been installed via vundle?

I posted on stackoverflow 12 hours ago. but with Vundle being new I guess no responses to confirm if this is occurring to others or its just a newbie mistake somehow.

http://stackoverflow.com/questions/8452779/vim-vundle-colorschemes-vimrc

**Comment by gerhard** [comment]
Hi, I'm having the same problem with https://github.com/gmarik/Vundle.vim/commit/0b28e334e65b6628b0a61c412fcb45204a2f2bab

```
Error detected while processing /Users/gerhard/.vimrc:
line   52:
E185: Cannot find color scheme ingretu
```

The ~/.vimrc

````
...
 51 Bundle 'gmarik/ingretu'
 52 colorscheme ingretu
...
```

Doing `:Bundle gmarik/ingretu` & then explicitly setting the colorscheme works fine.

```
vim --version

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep  9 2014 16:30:51)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

**Comment by gerhard** [comment]
Changing `vundle#begin()` to `vundle#rc()` fixed this problem for me. This README.md change was introduced in e7660d50f3c71b0805a376585bd55995e4f3f95b .

I can't be the only one having this problem, there is nothing special about my environment. Just stock OS X 10.10 with stock vim (see previous comment).

I have tested the `vundle#begin()` and can confirm the same issue on homebrew vim:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 13 2015 14:26:44)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/var/rbenv/versions/2.2.0/lib  -fstack-protector -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby-static -framework CoreFoundation -lobjc -L/usr/local/var/rbenv/versions/2.2.0/lib
```

**Comment by gerhard** [comment]
I found my mistake: `vundle#end()` appeared after `colorscheme ingretu`.

Is there any reason why I shouldn't be using `vundle#rc()`?

**Comment by jdevera** [comment]
Speed. if you use `rc` then every plugin is available immediately after it's `Plugin` line, but this has the cost of modifying the runtimepath twice for each plugin. With `begin`/`end`, every `Plugin` line adds the plugin to a temporary list that is then applied at once to the runtimepath with `end`.

**Comment by gerhard** [comment]
Sold. Thanks!

**Comment by mikey-** [comment]
I'm having the same issue but I'm using `vundle#begin()` and my `vundle#end()` are in the right places (here's my .vimrc: http://pastebin.com/sPfrUp8F)

also, im using osx 10.10.1

also here's what I'm seeing:
```
mikey$ vim ~/.vimrc
Error detected while processing /Users/mikey/.vimrc:
line   72:
E185: Cannot find color scheme 'solarized'
```

let me know if there is other info you need :)

**Comment by gerhard** [comment]
Did you actually install the plugins?

**Comment by tomofumikitano** [comment]
You should use 'altercation/vim-colors-solarized' , not 'altercation/solarized'

**Comment by mikey-** [comment]
haha yeah I installed the plugins and other plugins work. 
I tried using altercation/vim-colors-solarized and I don't get the error but the colorscheme doesnt work (everything is black and white) :\ 

Just wondering, why can't I use alercation/solarized? I use it on a machine thats running Ubuntu and it works fine. 

here is the result of `:scriptnames` http://pastebin.com/udbihS89

**Comment by mikey-** [comment]
Never mind, I got vim-colors-solarized working, thanks for the tip!
I'm so silly, I had:
```
colorscheme solarized
set background=dark
syntax enable
```

lol when I should have had:
```
syntax enable
set background=dark
colorscheme solarized
```
v silly of me. I would still like to know why I shouldn't use alercation/solarized

Anyway, thanks (: y'all are the best

**Comment by tomofumikitano** [comment]
Glad to hear that.

https://github.com/altercation/solarized#editors--ides

altercation/solarized hosts all the code for many different IDEs while altercation/vim-colors-solarized hosts only vim portion which has autoload directory on top for Vundle or other vim plugin manager.

**Comment by mikey-** [comment]
ah yess that makes sense (: thanks  for that

**Comment by DavidPesticcio** [comment]
I had the same issue - then I found this :smiley: - https://stackoverflow.com/a/34165694/1506858

> Your vimrc is supposed to be here:
> $HOME/.vimrc
> or there, if you use Vim 7.4 or newer:
> $HOME/.vim/vimrc
