### ISSUE TITLE
Vundle to add to .gitsubmodule

### ISSUE THREAD

**Issue by cwood** [VundleVim/Vundle.vim#145]
Hey,

Thanks for vundle I love it. However it would be nice if it could figure out if it was under git itself so when its added to another git repo it can target the remote modules. Right now I am doing it manually but wonder if you could make it so vundle does it automatically. 

Thanks!

**Comment by trygveu** [comment]
Hi @cwood, do you still consider this a feature that you would want? 

Isn't this better handled if you use a framework for dotfiles, which run the install job for you? https://dotfiles.github.io/

**Comment by wsdjeg** [comment]
there is no need add .vim to git repo,you can add vimrc_vundle to repo,then ln -s /path to/vimrc_vundle ~/vimrc

**Comment by trygveu** [comment]
I agree @wsdjeg, there are better ways to handle this. In my opinion this issue should be closed, together with #116 #226 and #198.

**Comment by wsdjeg** [comment]
thank you ,i just want to reduce duplication of repo!

**Comment by cwood** [comment]
I am actully not using vundle anymore but thanks anyway
