### ISSUE TITLE
FTDetect files not getting sourced

### ISSUE THREAD

**Issue by ghost** [VundleVim/Vundle.vim#16]
I am using my vim-slim plugin with vundle.

When I just use it with vundle, it ignores the ftdetect (It appears since the highlighting does not kick in) but when I manually run the commands out of the ftdetect file (IE :autocmd BufNewFile,BufRead *.slim set filetype=slim) and then open the slim files it loads the syntax highlighting.

Is there any reason that vundle would be ignoring the ftdetect directory?

**Comment by sharat87** [comment]
This might help someone later...

If moving `filetype plugin indent on` to after `vundle#end` doesn't fix it for you, try moving `syntax on` also to after the call to `vundle#end`. All the vundle configuration doesn't have to be in one place if you move both `filetype plugin indent on` and `syntax on` below `vundle#end`.

**Comment by pelodelfuego** [comment]
+1 on sharat87 solution.
It is related to a lot on utliSnip issues.
Maybe the Readme.md should be updated to remove any doubt ?

**Comment by elrrrrrrr** [comment]
+1 on sharat87 solution.

**Comment by johntyree** [comment]
@elrrrrrrr please don't add +1 comments on issues unless you have new information that people should read. A lot of emails get sent every time someone makes a comment.
