### ISSUE TITLE
Git Commit Problem: "error: There was a problem with the editor 'vi'"

### ISSUE THREAD

**Issue by codyaray** [VundleVim/Vundle.vim#167]
I'm just starting to use Vundle and I'm running into an error when editing a Git message using the .vimrc setup from the README. When I try to save any git message in vim, I get the following error.

```
$ git commit
error: There was a problem with the editor 'vi'.
Please supply the message using either -m or -F option.
```

I've tracked this down to the initial `filetype off` directive (marked as required in the README). I don't understand why its causing this issue, but after commenting out the line, but this re-enabled Git commit editing in vim.

Can you shed some light on why its "required" to disable filetype detection before using vundler? And then to re-enable it (using `filetype plugin indent on`) later on?

FWIW, my vim version:

```
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 24 2011 20:00:09)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile -python 
-python3 +quickfix +reltime -rightleft -ruby +scrollbind +signs +smartindent 
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

**Comment by zyyw** [comment]
git config --global core.editor $(which vim)
This works in my case. Platform Mac OS X 10.9.5

**Comment by danielarndt** [comment]
Just chiming in to say this only happened to me *after* installing the homebrew version of vim. Worked fine before hand. Hopefully that's a hint.

**Comment by flaing** [comment]
I tried <code>git config --global core.editor $(which vim)</code> and it doesn't work for me.

The error message are: 

> /usr/bin/mate -w: /usr/bin/mate: No such file or directory
> error: There was a problem with the editor '/usr/bin/mate -w'.
> Please supply the message using either -m or -F option.

**Comment by Alhadis** [comment]
Just hit this, thank God for you guys. Solution works. :D

Like many others posting here, I'm using a version of Vim installed by Homebrew on OS/X.

The problems wouldn't be happening because Git's not reading symlinked $EDITOR paths, would it...? Homebrew executables are symlinked to `/usr/bin/`, sooo...

**Comment by enderahmetyurt** [comment]
thank you @ruebenramirez 🎉

**Comment by returnvoid** [comment]
git config --global core.editor $(which vim) worked for me too

**Comment by ritabugking** [comment]
git config --global core.editor /usr/bin/vim 
solved my problem. Thanks!

**Comment by andreaswolf** [comment]
I had this problem repeatedly when using ":W" by error instead of ":w". Using ":w" after having used ":W" once did not fix the problem, after saving and closing, the commit message was lost.

`git config --global core.editor /usr/bin/vim` fixed it reliably for me.

**Comment by tdas** [comment]
For me setting core.editor wasnt sufficient. I had a complicated .vimrc which had the following.
`filetype off`
I replaced that with 
```
filetype on
filetype off
```
It looks dumb but this totally worked. See @cameronr comment for more detailed explanation. Kudos to him!

**Comment by azhong00** [comment]
how to recover the lost git message when this happened?

**Comment by dreyks** [comment]
@azhong00 you can find it int `.git/COMMIT_EDITMSG`

**Comment by jacwah** [comment]
A more general solution is to set `export EDITOR=$(which vim)` in your `.bashrc`. Git will use this environment variable if `core.editor` is not set and other programs will know to use Vim too.

**Comment by abdulashaka** [comment]
i have commit problem with my git cmd

**Comment by JDiPierro** [comment]
@cameronr's solution [here](https://github.com/VundleVim/Vundle.vim/issues/167#issuecomment-55700048) is the best IMO. I ran into this with a git commit as well but then I also it hit using `kubectl edit` on a kubernetes resource. The `git config` workaround will fix the problem in git but it'll still occur in other instances that invoke an editor and use the output. Setting `filetype on` before setting `filetype off` in the `.vimrc` resolves it in all situations.

**Comment by wys1996** [comment]
this works for me too

**Comment by jianzhangbjz** [comment]
Encounter this issue in Mac, the `git config --global core.editor $(which vim)` did NOT work for me, but setting `~/.vimrc` works! Add below in it:
```vim
filetype on
filetype off
```

**Comment by rkeet** [comment]
I know this is an old one, but it helped out. 

On Windows, make it something like so to fix:

`$ git config --global core.editor "C:/Program\ Files\ \(x86\)/Notepad\+\+/notepad\+\+.exe"`

If you copy your path from Windows Explorer, make sure to replace all Directory Separators (`\`) with forward slash `/` and use the back slash to escape any non-alphanumeric charachters, such as in the example above for space char, `+`, `(` and `)`.

**Comment by RelentlessExploration** [comment]
> `git config --global core.editor $(which vim)`

For people who prefer `nvim`, use `git config --global core.editor $(which nvim)`

**Comment by ayush-mandowara-bst** [comment]
I get error `Unknown function: plug#begin` when I set the vim editor path correctly :( Please help.

**Comment by dockerlead** [comment]
For those who uses `vim` or `nvim`, I recommend:
```bash
git config --global core.editor notepad
```

**Comment by Visual-Dawg** [comment]
> Also, in fish shell, you may want to use: `git config --global core.editor (which vim)`
Why does `nvim` not work in fish shell?
Setting it to `vi` (I dont have vim) fixed it for me, but I vastly prefer my Neovim setup

**Comment by ankitmukhia** [comment]
> `git config --global core.editor $(which vim)` make sense to me

worked for me as will, did ```git config --global --core-editor nvim``` for my nvim preference env
