### ISSUE TITLE
:BundleInstall and :Bundles throw errors, don't work

### ISSUE THREAD

**Issue by maxcountryman** [VundleVim/Vundle.vim#175]
Hi,

I've been banging my head against a wall with this for the last several hours: basically I can't seem to get Vundle to work at all.

I'm running OS X 10.7.3, MacVim Snapshot 64. I've cloned Vundle into ~/.vim/bundle/vundle. Here's my vimrc for reference: http://pastebin.com/raw.php?i=tXhZJ1bH

The most persistent error is related to /var not being writable: "Can't open file: /var/folders/q4/..." (Although the specific path is owned by be user and other apps are using /var just fine.) Also I see "Error fetching scripts!" with :Bundles. There's some other error about undefined variables that pops up now and then.

I finally decided to just rm -rf ~/.vim and start from scratch. But the same issues persist. Any idea what might be causing this?

**Comment by mascip** [comment]
`set shell=/bin/bash` fixed it for me too, in ArchLinux

**Comment by dopatraman** [comment]
Many thanks for this.

**Comment by jueqingsizhe66** [comment]
My Windows10  Solution:
  put the git in the path environment

and add "set shell=git"  in the vimrc  

ok. Everything works fine.

**Comment by YaoXuanZhi** [comment]
2333, this plug-in relies on git, so make sure that you can find git in system environment variables.

**Comment by arwildo** [comment]
If you're using Windows, delete the set shell=powershell, it only works at cmd terminal
