### ISSUE TITLE
Vundle is not working on Mac OS X Lion (10.7.4)

### ISSUE THREAD

**Issue by wael34218** [VundleVim/Vundle.vim#182]
Each time vim starts it prompts the following error :

Error detected while processing /Users/waelfarhan/.vimrc:
line    5:
E117: Unknown function: vundle#rc

I tried installing vundler on mac build in vim (7.3), MacVim and https://code.google.com/p/vim/ (7.3.556). All of them had the same problem.

Keep in mind that my .vimrc is the same as the readme file.

Tried it on Fedora (13) vim 7.2.411 and 7.3.55 worked perfectly.

**Comment by eiger3970** [comment]
Not working on El Capitan (10.11.1) https://github.com/VundleVim/Vundle.vim/issues/668
