### ISSUE TITLE
Handle repeated vim-scripts plugin names

### ISSUE THREAD

**Issue by fisadev** [VundleVim/Vundle.vim#183]
The mechanism to install plugins from vim.org/scripts uses the name of the plugin as identifier, but there are _many_ repeated names of plugins. There is no way to diferentiate one plugin from another with the same name.
Some examples with :BundleSearch python.vim

**Comment by wmayner** [comment]
For anyone who's having this issue with the two `python.vim` bundles ([here](http://www.vim.org/scripts/script.php?script_id=30) and [here](http://www.vim.org/scripts/script.php?script_id=790)), Dmitry Vasiliev has made it available from [this repo](https://github.com/hdima/python-syntax) (per [this tweet](https://twitter.com/hdima/status/333681764792946688)), so you can get it from there with `Bundle 'hdima/python-syntax'`.
