### ISSUE TITLE
Some plugins not loading on windows

### ISSUE THREAD

**Issue by eduardocereto** [VundleVim/Vundle.vim#193]
I have the exact same setting on Ubuntu and Windows. On Windows some plugins load just fine, and some don't. The plugins that are not loading at the moment are sparkup and NERDtree.

Here's my rtp

```
C:\Users\eduardocereto\vimfiles\bundle\vundle,C:\Users\eduardocereto\vimfiles\bundle\vim-fugitive,C:\Users\eduardocereto\vimfiles\bundle\vim-easymotion,C:\Users\eduardocereto\vimfiles\bundle\vim-powerline,C:\Users\eduardocereto\vimfiles\bundle\sparkup\vim\,C:\Users\eduardocereto\vimfiles\bundle\nerdtree,C:\Users\eduardocereto/vimfiles,C:\Program Files (x86)\Vim/vimfiles,C:\Program Files (x86)\Vim\vim73,C:\Program Files (x86)\Vim/vimfiles/after,C:\Users\eduardocereto/vimfiles/after,C:\Users\eduardocereto/vimfiles/bundle/vundle/,C:\Users\eduardocereto\vimfiles\bundle\vundle/after,C:\Users\eduardocereto\vimfiles\bundle\vim-fugitive/after,C:\Users\eduardocereto\vimfiles\bundle\vim-easymotion/after,C:\Users\eduardocereto\vimfiles\bundle\vim-powerline/after,C:\Users\eduardocereto\vimfiles\bundle\sparkup\vim\/after,C:\Users\eduardocereto\vimfiles\bundle\nerdtree/after
```

:BuildInstall runs fine and says installed all my plugins. I can see that the plugins are cloned inside my vimfiles directory. EasyMotion and powerLine work just fine. I see no errors or anything when I open Vim. Been bashing my head on this one for a while.

**Comment by Davidrjx** [comment]
even though Plugin ''rstacruz/sparkup', {'rtp': 'vim'} is placed after Plugin 'scrooloose/nerdtree', NERDTree is not working why some core NERDTree vim files are loaded in wrong runtimepath order. 
Here,what i want to know/get is right solution to resolve the problem at Vundle's end.
