### ISSUE TITLE
[Bug] E441: There is no preview window

### ISSUE THREAD

**Issue by neersighted** [VundleVim/Vundle.vim#204]
I am running into a rather strange error.

Upon running `:Bundle*`, I get this error (copied and pasted from `:messages`):

```
"vimrc" 1134L, 45680C
E441: There is no preview window
Error detected while processing function vundle#installer#new..vundle#scripts#view:
line    5:
E480: No match: [Vundle] Installer
line    7:
E441: There is no preview window
```

Vundle then precedes to prepend it's usual output to the current buffer, and then run it (it also applies it's local binds, and will execute any lines in the buffer if you run `:BundleInstall`).

I have tried debugging this by removing/swapping out Bundles, but I have had no luck so far. I am not sure what is causing this problem (conflicting Bundle?), as it will run fine on the initial install.

My vimrc is available in my [dotfiles repo](https://github.com/neersighted/._/blob/master/vim/vimrc).

**Comment by Leandros** [comment]
I had this issue, after installing v46 of [taglist](https://github.com/vim-scripts/taglist.vim).

**Comment by Leandros** [comment]
I'm having this issue again, taglist wasn't the culprit, it just coincidentally fixed it. Bug also appears with a minimal `.vimrc`.

**Comment by gogoengie** [comment]
Same issue. Removed `set wildignore+=*/tmp/*,*.so,*.swp,*.zip` from my vimrc and re-ran `:PluginUpdate` with no errors. Restored the `wildignore`, and `:PluginUpdate` continues to run without errors, so something about the issue is stateful.
