### ISSUE TITLE
Help Tags Problem

### ISSUE THREAD

**Issue by jherdman** [VundleVim/Vundle.vim#21]
Hi. I'm attempting to fully switch from Pathogen, and I've noticed the following error when running `:BundleInstall`:

<pre>
Error detected while processing function vundle#installer#install..vundle#instal
ler#helptags..<SNR>53_helptags:
line    1:
E150: Not a directory: `=a:rtp.'/doc'`
</pre>

I've followed the instructions closely, but something seems to be amiss. Any ideas?

**Comment by prophittcorey** [comment]
Also, it appears if you `*/bundle/*` in your wild ignore the help tags command will fail. I had to remove it from mine. I used that ignore for a certain type of project. Took me a while to figure out why help tags was failing!
