### ISSUE TITLE
Problem with vim-coffee-script

### ISSUE THREAD

**Issue by gapthemind** [VundleVim/Vundle.vim#210]
Hi,

I was having problems getting kchmck/vim-coffee-script to work with vundle. I have found a solution, so I am just reporting this in case something needs to be fixed, and in case someone else runs into the problem.

The sort version of the story is that I need to put the 'syntax on' after Bundle 'kchmck/vim-coffee-script' or otherwise the plugin does not work correclty. While debugging, I tested the plugin with pathogen. There, the plugin works fine no matter where in the vimrc the 'syntax on' is located.

BTW, vim-coffee-script seems to be the only plugin with this problem, as all the other ones work properly.

The symptoms:
- Opening a coffee file does not syntax highlight and :scriptnames does not report the vim-coffee-script scripts
- After opening a coffee file and running 'set filetype=coffee', sysntax highlighting works, and the scripts are reported by :scriptnames (e.g. /Users/vimtest/.vim/bundle/vim-coffee-script/ftplugin/coffee.vim)
- Adding 'autocmd BufNewFile,BufRead *.coffee set filetype=coffee' to my vimrc after the Bundle 'kchmck/vim-coffee-script' line also solves the problem. Note that that line can be found in the scripts ftdetect/coffee.vim file.
- After opening vim, 'set rtp returns' runtimepath=~/.vim/bundle/vundle,~/.vim/bundle/vim-coffee-script,~/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfiles/after,~/.vim/after,~/.vim/bundle/vundle/,~/.vim/bundle/vundle/after,~/.vim/bundle/vim-coffee-script/after

**Comment by tex1337** [comment]
I have done many different iterations of this, none of which worked until I realized that the instructions given are maybe out of date / erroneous.

The easiest mechanism to follow that fixes all the issues I had was to have it in the following order:

- Only call set nocompatible, filetype off, set rtp+=...
- Call vundle#begin()
- Plugin... lines
- Call vundle#end()
- It is at this point it is safe to call all your set, colorscheme etc
- End with filetype plugin indent on, syntax on

I think that the plugin management stuff is meant to come before the vim native stuff as this package is sensitive to that.
