### ISSUE TITLE
Error: Malformed value for push.default: simple

### ISSUE THREAD

**Issue by torifat** [VundleVim/Vundle.vim#251]
`vundle` is using the old `git` from OSX. So, it can't recognize the new config `push.default: simple`. So, It fails during the `git init`.

---

If you face this error set `git config --global push.default matching` for now.

**Comment by a652** [comment]
Thanks
`git config --global push.default matching` worked

**Comment by samkguerrero** [comment]
Thank you, torifat. it worked.

**Comment by 2pravin7** [comment]
> `vundle` is using the old `git` from OSX. So, it can't recognize the new config `push.default: simple`. So, It fails during the `git init`.
> 
> If you face this error set `git config --global push.default matching` for now.

This worked! Thanks

**Comment by TenzinNsut** [comment]
> `vundle` is using the old `git` from OSX. So, it can't recognize the new config `push.default: simple`. So, It fails during the `git init`.
> 
> If you face this error set `git config --global push.default matching` for now.

Thanks!

**Comment by Star-cj** [comment]
> `vundle` is using the old `git` from OSX. So, it can't recognize the new config `push.default: simple`. So, It fails during the `git init`.
> 
> If you face this error set `git config --global push.default matching` for now.

thanks so much. It worked
