### ISSUE TITLE
Error processing: 'plugin_name' 

### ISSUE THREAD

**Issue by arnsa** [VundleVim/Vundle.vim#273]
I've just installed Vundle for the very first time. Before that I've used pathogen and everything worked fine. Now I've configured my .vimrc file and when I run vim and type :BundleInstall, some of the plugins couldn't be processed. I get the following message: Error processing: 'plugin_name'. Vundle couldn't process these plugins: autotag, ctags, taglist and gdbmgr.

My setup is:

set nocompatible
set rtp+=~/.vim/bundle/vundle
call vundle#rc()
filetype off

Bundle 'vundle'
... -- other plugins

**Comment by ukko** [comment]
or git is not installed
