### ISSUE TITLE
Asking for Github username/pw using Bundle 'shawncplus/phpcomplete'

### ISSUE THREAD

**Issue by davidosomething** [VundleVim/Vundle.vim#284]
For some reason I'm getting prompted fora GitHub username/pw when adding
Bundle 'shawncplus/phpcomplete'

maybe a vundle issue, crossposting

**Comment by Californian** [comment]
This is still a bug. It freezes vim, when it should instead notify the user of a `404`. Vim has to be externally killed, and no username can even be entered.
