### ISSUE TITLE
Is there an easy way to disable ( without uninstalling ) plugins?

### ISSUE THREAD

**Issue by kshenoy** [VundleVim/Vundle.vim#289]
First of all let me congratulate you on a great plugin. For a long time I was satisfied with Pathogen and thought I didn't have any reason for switching. But now that I'm used to letting Vundle handle the installation and update of the plugins, I don't think I'll ever look back.

This isn't actually an issue but more a question. Pathogen uses an array g:pathogen_disabled[] in which you can add the names of plugins that you don't want added to the runtimepath. Is there something similar in Vundle?

I know I can just comment out the line "Bundle <someplugin>" in my .vimrc and run `:BundleClean` and `BundleInstall` again to re-install but is there something which doesn't (un)install the plugins and rather acts only on the runtimepath?

Thanks

**Comment by rafaelgm** [comment]
Hi. I know it's an old thread, but I would like to give my 2 cents. :)

I have both Windows and Linux (Ubuntu) and try to keep `%USERPROFILE%\.vim\bundle` and `~/.vim/bundle` in sync, respectively, so I can have the same work environment on both systems and it also works as backup solution.

But there are cases where the plugins folder cannot be the same. For example, I use [YouCompleteMe](https://github.com/Valloric/YouCompleteMe). On Ubuntu, I use the git source, and build it on Ubuntu. But on Windows, I have to use a precompiled package (actually I have two of them, one for 32-bit gVim and the other for 64-bit).

This is what I did on `.vimrc` (it's the same file on Windows/Linux, they're kept it in sync):

    if has("unix")
        Plugin 'Valloric/YouCompleteMe'
    elseif has("win64")
        Plugin 'YouCompleteMe_win_64', {'pinned': 1}
    elseif has("win32")
        Plugin 'YouCompleteMe_win_32', {'pinned': 1}
    endif

It works fine. Problem is: if I run `PluginClean` on one of the scenarios above, it'll ask me to remove the other two plugins, which is kind of annoying.

That said, I agree with the "disable" option. Then I could tell it to "ignore" the other two folders, on each case. As a workaround, I'll probably use the syntax `call vundle#begin('~/some/path/here')` and use two different paths, one for Windows and another for Linux. But I see two problems: one is I'll have many plugins duplicated on both systems. The second problem is I still have the gVim 32/64-bits difference on Windows, and I would not like to create three copies of everything! :confused: 

Anyway, thanks for the great plugin, it's very powerful and easy to use. :smile:

**Comment by devvmh** [comment]
For those coming from Google, there is a way: http://stackoverflow.com/a/6706997/5332286
