### ISSUE TITLE
Plugins do not install

### ISSUE THREAD

**Issue by jbeja** [VundleVim/Vundle.vim#294]
I follow the instruction and after doing :BundleInstall! is giving me this similar output every time that is trying to install a Bundle:

Error detected while processing function vundle#installer#new..<SNR>29_process..vundle#installer#run..vundle#installer#install
..<SNR>29_sync..<SNR>29_system:
line    1:
E484: Can't open file /tmp/vUZSGlg/6
Error detected while processing function vundle#installer#new..<SNR>29_process:

**Comment by JustinHoyt** [comment]
jlk erlsjiwj dsfa jkjkjllljkjkj
