### ISSUE TITLE
private repo on bitbucket

### ISSUE THREAD

**Issue by weaksauce** [VundleVim/Vundle.vim#331]
is it possible to use a private repository with vundle? I have tried every configuration possible but still haven't been able to get it to work correctly. I can access my bitbucket repo via the command line and a ssh alias using the key that I want to use but any iteration of that fails when doing a :BundleInstall

**Comment by hashken** [comment]
By adding a Hostname field (with git as value) in your SSH config, you can just use:

    Bundle "bitbucket:weaksauce/testPlugin"
