### ISSUE TITLE
Support for locking onto a Tag or Branch

### ISSUE THREAD

**Issue by jherdman** [VundleVim/Vundle.vim#35]
Lately I'm getting burned by installing Vim plugins at HEAD instead of a stable branch or tag version. It'd be nice to be able to lock onto a stable tag or branch to prevent this from happening. Is this a possibility?

**Comment by jwhitley** [comment]
The use case that brought me here: I've just fixed a bug in a popular plugin and submitted a PR for a fix.  I have no idea if/when my branch will be pulled, but I'd like to use it in the meantime.  I could simply merge to my master branch, but I prefer to track upstream unless/until I determine that upstream isn't going to respond for whatever reason.  Syntax similar to @firedev's above, or @Xerkus' treeish support, or similar would be very handy.

A related use-case: I'd like to switch to an experimental branch for a plugin, either one I'm developing myself or someone else's I'm helping to test.  I could just use a local repo, but I'm often working across multiple systems or VMs while that plugin development proceeds.

**Comment by MarcWeber** [comment]
VAM's situation is: you can pass revisions along with plugin names, and you could overwrite the update hook to change the branch. However VAM has another way: You can define ~/overrides and define a function which looks in ~/overrides for plugins first, then in ~/.vim/bundle like directory. Thus by either setting or not setting a custom function telling VAM about plugin locations by name you get something similar, even better. Thus it could be done, but nobody has done it yet. In the Vundle case probably there is also a way to change the bundle directory. Changing the directory would allow you to keep unclean repositories on disk and run multiple vim instances with different behaviors which could be useful when coding ..

**Comment by mcandre** [comment]
+1

**Comment by cknoerle** [comment]
:+1:

**Comment by stevschmid** [comment]
:+1:

**Comment by Peeja** [comment]
A GitHub etiquette PSA: Please refrain from adding +1s to already-popular issues. It spams everyone interested in the issue and contributes nothing to the discussion. Gauging interest is important at the beginning of a feature discussion, but at this point no amount of +1ing will make this feature happen any faster.

(Apologies for further spamming the subscribers on this issue. I hope this post results in stopping more email than it generates.)

**Comment by mcandre** [comment]
> A GitHub etiquette PSA: Please refrain from adding +1s to already-popular issues. It spams everyone interested in the issue and contributes nothing to the discussion. Gauging interest is important at the beginning of a feature discussion, but at this point no amount of +1ing will make this feature happen any faster.

+1

**Comment by jalcine** [comment]
That was unnecessary @mcandre.

**Comment by WoLpH** [comment]
Personally I'd prefer a syntax like this:
```
Bundle 'gmarik/Vundle.vim@branch'
```

Where `branch` could be a tag or specific commit as well :)

**Comment by jdevera** [comment]
Since this seems to be quite the active issue I'll mention here that I'm no longer working on Vundle.

So if somebody really wants to see this feature, they could perhaps give it a try. The PRs that are currently attempting to implement this feature all fall short in one or another, so maybe it's just a matter of picking from all of them.

All the best.

**Comment by interfect** [comment]
I think this should be re-opened. It looks like the syntax `user/repo@version` added in #604 doesn't work as of b255382d6242d7ea3877bf059d2934125e0c4d95, and the commit 272d9fe2bf0645ff50e1b782fbee67314ec8e437 from #604 is not in the current history.
