### ISSUE TITLE
Dev questions

### ISSUE THREAD

**Issue by marlun** [VundleVim/Vundle.vim#386]
1. I would like a list of all the supported ways of naming a plugin (what comes after Bundle in your vimrc). Maybe I should call it configuring a plugin?

2. The reason I'm asking is because I'm trying to understand the if statement

        if    arg =~? '^\s*\(gh\|github\):\S\+'
        \  || arg =~? '^[a-z0-9][a-z0-9-]*/[^/]\+$'

    The second one is for <github-user>/<repo-name> but what is the first one for?

**Comment by ryanoasis** [comment]
@marlun I assume by now this is no longer a question :laughing: 

I vote to close this issue, any seconds? @btreeinfinity @silfverstrom @gmarik

**Comment by gmarik** [comment]
@ryanoasis :+1: 
Feel @marlun feel free to keep discussion going tho…
