### ISSUE TITLE
Think about how to collaborate with VAM/vim-pi/NeoBundle

### ISSUE THREAD

**Issue by MarcWeber** [VundleVim/Vundle.vim#387]
:) Thanks. You're welcome

**Comment by trygveu** [comment]
I vote for closing this issue as it has been left untouched for more than a year, and it is not actionable. @btreeinfinity @ryanoasis @silfverstrom .

**Comment by ryanoasis** [comment]
Yeah good point and there are many other issues and/or PRs that are needing attention.

I vote close as well unless @gmarik wants to keep it open for a specific reason.

**Comment by trygveu** [comment]
@wsdjeg asked in #608 why NeoBundle and Vundle are two seperate projects, and @vyp provided a good answer:

> @wsdjeg If I recall correctly, gmarik preferred to keep Vundle simple, but Shougo wanted more  features, hence another plugin manager. That's the great thing about free software, we are allowed to have more choices if someone is technical enough to hack on it.
>
> If you are having a hard time choosing, I suggest either start with Vundle (this) or vim-plug. And if you find out later that you want more features, try neobundle.

I believe it is an important point to observe that NeoBundle was forked from Vundle. Shougu had a different philosophy that didn't fit with the _simple_ principle of Vundle, and it has been developed into a more complex and feature rich system. This is part of the beauty of open source.

**Comment by ryanoasis** [comment]
Good points and info.

Closing given it is not actionable and old. Reopen later if it really needs to be.
