### ISSUE TITLE
Need to run PluginInstall or :BundleInstall each time.

### ISSUE THREAD

**Issue by raghur** [VundleVim/Vundle.vim#430]
hi,
lately, there seems to be a problem with Vundle. Basically, some plugins aren't loaded unless I issue :PluginInstall or :BundleInstall each time after starting gvim. My vim config is at: https://github.com/raghur/vimfiles

Gvim 7.4 32bit on Windows7x64  with Huge features and patches 1-250

**Comment by denten** [comment]
Having the same problem when changing from `call vundle#rc()` to `call vundle#begin()`. Airline stops loading. Reverting back to  `call vundle#rc()` fixes things again.

**Comment by dileepkr** [comment]
I had to put the vim plug statements in .vimrc not .gvimrc .
This fixed my issue.
