### ISSUE TITLE
BundleUpdate does not work after updating vim to patch 274

### ISSUE THREAD

**Issue by FvD** [VundleVim/Vundle.vim#470]
After updating vim to include patches up to 274 BundleUpdate no longer works and throws the following two errors:

```
E117: Unknown function: g:shellesc_cd
E15: Invalid expression: g:shellesc_cd(cmd)
```

This seems to be the similar to the problem reported here to the vim group on google: https://www.mail-archive.com/vim_dev@googlegroups.com/msg28293.html but I could not find a relevant issue on github.

**Comment by gmaghera** [comment]
Thank you for the fix!  I've been pestered by this issue for a while now.
