### ISSUE TITLE
PluginSearch gives an error on Mac OS X

### ISSUE THREAD

**Issue by bulkan** [VundleVim/Vundle.vim#477]
Hi all,

PluginSearch does not seem to work for me. I typed `PluginSearch test`

Vim is installed via homebrew `vim: stable 7.4.273, HEAD`

Here is the error message from Vundle

![screen shot 2014-05-18 at 7 20 07 pm](https://cloud.githubusercontent.com/assets/13985/3007127/fdc89338-de6d-11e3-80df-b49935f9fb61.png)

**Comment by noscripter** [comment]
c #599
