### ISSUE TITLE
Name Collision for Plugin

### ISSUE THREAD

**Issue by maruf89** [VundleVim/Vundle.vim#494]
It's showing this obnoxious error after running a script that has always worked perfectly for me before.

``` bash
Error detected while processing function vundle#config#bundle..<SNR>8_check_bundle_name:
line    2:
Vundle error: Name collision for Plugin jistr/vim-nerdtree-tabs. Plugin jistr/vim-nerdtree-tabs previously used the name "vim-nerdtree-tabs". Skipping Plugin jistr/vim-nerdtree-tabs.
Press ENTER or type command to continue
```

Not very familiar with vundle, I tried deleting the ~/.vim/bundles and reinstalling vundle and I can't find any similar issues. Not sure with jist/vim-nerdtree-tabs is locate, I delete the bundle and the error still persists.

Honestly I just want the error to stop showing and not need to press enter, because it still works with nerd tree

**Comment by KundanKumar0** [comment]
On windows 10, I had a file named ._vimrc.un~. Renaming this file resolved the issue for me.

**Comment by Zepeng-Mu** [comment]
I also encountered this problem. However, I do not have the plugin line in my .vimrc

**Comment by liuyangcharlie** [comment]
> I also encountered this problem. However, I do not have the plugin line in my .vimrc

Me, too
