### ISSUE TITLE
"Argument required: Bundle"

### ISSUE THREAD

**Issue by mattyoho** [VundleVim/Vundle.vim#50]
Pulling latest head results in a slew of the error "Argument required: Bundle" being spat out upon processing my bundle config file. Moving back to the commit (06088de2) prior to "Allow comments after Bundle declarations" (d840b240) causes the error to cease.

Mac OS X 10.6
MacVim 7.3.53
Using https://github.com/edgecase/vim-config

**Comment by jfelchner** [comment]
@gmarik wow man, the fact that double quotes _can't_ be used is pretty counterintuitive.  It'd be great if there was at least a warning.  I hit this and spent about an hour trying to figure it out.

Thanks for the awesome plugin!
