### ISSUE TITLE
:BundleClean removes vundle itself

### ISSUE THREAD

**Issue by skuroki** [VundleVim/Vundle.vim#52]
I installed vundle following README, such as:

```
$ git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
```

and wrote .vimrc, such as:

```
set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'rails.vim'
Bundle 'quickrun.vim'
Bundle 'Shougo/unite.vim'
Bundle 'Shougo/neocomplcache'

filetype plugin indent on     " required
```

when I executed :BundleClean, and answered y to the confirmation, vundle itself was removed, such as:

```
:!rm -rf '/home/s-kuroki/.vim/bundle/vundle'
```

I think vundle itself should not be removable by :BundleClean. or did I something in the wrong way?

**Comment by BatmanAoD** [comment]
I still have this problem using the latest Vundle version, with the line `Bundle 'gmarik/Vundle.vim' present.

Output of `BundleInstall` (note that `Vundle.vim` is included):

![bundleinstall](https://cloud.githubusercontent.com/assets/2313807/6258320/f23e7168-b784-11e4-94b4-85b976807c30.png)

Output of `BundleClean`:

![bundleclean](https://cloud.githubusercontent.com/assets/2313807/6258328/fa2674fc-b784-11e4-8036-523945f74824.png)

**Comment by BatmanAoD** [comment]
Oops, there was a case difference--I had `vundle.vim` instead of `Vundle.vim` in my `.vimrc`.
