### ISSUE TITLE
Error loading plugins with DOS formatting (^M problem)

### ISSUE THREAD

**Issue by oryband** [VundleVim/Vundle.vim#6]
Hi.

I think there is a problem loading plugins with _DOS_ formatting.

For example, add this bundle to your .vimrc and install it: `Bundle "CSS3-Highlights"`

Then, try to open a *.css file, and you will get the following errors:

```
Error detected while processing /Users/ory/Documents/dotfiles/vim/bundle/CSS3-Highlights/syntax/css.vim:

line    8: E492: Not an editor command: ^M
line   11: E15:  Invalid expression: !exists("main_syntax")^M
line  303: E488: Trailing characters
line  309: E171: Missing :endif
```

This happened on another plugin as well: `Bundle "Better-CSS-Syntax-for-Vim"`

I'm using both MacVim & Vim, OSX 10.6.6 Snow Leopard.

Thanks very much for your time! Your plugin is amazing!
Ory

**Comment by PajaroImitador** [comment]
Hi! I have the same problem with lots of vim plugins that had been written in Windows. First I tried to change my my terminal config to be compatible with .vim files written in Windows, but I wasn't successful. 

So I wrote a small code on python that I think might work for most linux users. It depends on dos2unix which is already installed in most linux distros. The code will assume that your .vim directory is under  /home/userName/.vim and it will find all .vim files under that directory and then run dos2unix -f file.vim. It works pretty good for me, hope this helps :D 

vimfix.py:
https://github.com/PajaroImitador/zsh_config/blob/master/vimfix.py
