### ISSUE TITLE
bundles don't seem to be installed properly

### ISSUE THREAD

**Issue by HuStmpHrrr** [VundleVim/Vundle.vim#606]
vundle doesn't seem to unpack bundles to take effect. for example, here is one of the bundles that I installed from vundle:
```
~/.vim/bundle$ tree vim-json-bundle/
vim-json-bundle/
├── ftdetect
│   └── json.vim
├── ftplugin
│   └── json.vim
├── indent
│   └── json.vim
├── README
└── syntax
    └── json.vim

4 directories, 5 files
```
and apparently:

```
:~/.vim$ tree syntax/
syntax/
└── erlang.vim

0 directories, 1 file
```
the installation didn't take effect at all.

did i operate wrongly?

**Comment by eliasdorneles** [comment]
Hm, what exactly is that you were expecting? What exactly do you mean by "the installation didn't take effect at all"? Is the json plugin not working?

Vundle works by creating plugin directories under `~/.vim/bundle/` and then sets vim's variable `runtimepath` to include all of them.

It doesn't "unpack" bundles under `~/.vim`, if that's what you were expecting.

**Comment by ryanoasis** [comment]
@HuStmpHrrr the plugins look to be installed correctly, are the plugins working for you in vim?

**Comment by HuStmpHrrr** [comment]
sorry for applying so late.

sorry about that, i wasn't correctly configuring it and the interface was different from the articles i read in the internet so i got confused.

things are fine now. thanks.
