### ISSUE TITLE
Plugins not loading

### ISSUE THREAD

**Issue by thetutlage** [VundleVim/Vundle.vim#613]
I am running macvim `7.4 ` with following `.vimrc` file inside by home directory , but plugins are not loading on startup

## .vimrc
```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'kien/ctrlp.vim'

call vundle#end()

filetype plugin indent on

set noswapfile
set guifont=Inconsolata\ for\ Powerline:h15
let g:Powerline_symbols = 'fancy'
set encoding=utf-8
set t_Co=256
set fillchars+=stl:\ ,stlnc:\
set term=xterm-256color
set termencoding=utf-8
```

**Comment by z3t0** [comment]
@thetutlage Is the above your entire vimrc? Have you installed the plugins? 
`:PluginInstall`

**Comment by thetutlage** [comment]
Yes above is the entire vimrc , and i did installed plugins using `:PluginInstall`

**Comment by z3t0** [comment]
Do the plugins load at all?
You may need to set the directory for Vundle to install plugins as they may be installing them somewhere else.

`call vundle#begin('~/some/path/here')`

**Comment by z3t0** [comment]
Try `call vundle#begin('~/.vim/bundle')`

**Comment by z3t0** [comment]
Solution: Place vimrc in the right directory.

**Comment by t3476** [comment]
I found that vim turn syntax off since 7.4 by default which is misleading that plugins aren't loaded. 
Append this in .vimrc
> syntax on

**Comment by Alexintosh** [comment]
I have the same problem.

**Comment by nfischer** [comment]
Could you please add the output of `ls ~/.vim/bundle/`. That would help debug the problem. What you *should* see, if everything's working properly, are folders for each of the vim plugins you're trying to install.

**Comment by blitzd** [comment]
Also having this same issue:

```
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

Plugin 'gmarik/Vundle.vim'
Plugin 'reedes/vim-thematic'
Plugin 'bling/vim-airline'

call vundle#end()
filetype plugin indent on
```

```
blitzd@deb:~$ ls ~/.vim/bundle/
vim-airline  vim-thematic  Vundle.vim
```

Vim 7.4, debian 8.2.

**Comment by gmarik** [comment]
no feedback. Closing…
