### ISSUE TITLE
I can't push to Github when using git protocol.

### ISSUE THREAD

**Issue by luochen1990** [VundleVim/Vundle.vim#615]
I found that when using git protocol on vundle, it changes my remote `origin`'s url from something like
```
https://github.com/userxxx/repoxxx.git
```
to
```
git://github.com/userxxx/repoxxx.git
```
, which makes github refused my push request.

and I found out the real reasion [here](http://stackoverflow.com/questions/7548661/git-github-cant-push-to-master), it saies that GitHub doesn't support pushing over the git protocol.

So maybe use an url like this would be more reasonable (when people using `Plugin username/repo` command with git protocol.
```
git@github.com:userxxx/repoxxx.git
```

**Comment by gmarik** [comment]
Again it's not Vundle's concern. if you want to push there's a [git configuration for this](https://github.com/gmarik/dotfiles/blob/00ec51e984104ab84daae5f40df154d9b8ab53a3/.gitconfig#L216-L220)

Closing.
