### ISSUE TITLE
url error in "autoload/vundle/config.vim"

### ISSUE THREAD

**Issue by zhuhan1236** [VundleVim/Vundle.vim#618]
The download url in line 164 of "autoload/vundle/config.vim" seems to be wrong. There is a duplicated "/" before "vim-scripts"

**Comment by gmarik** [comment]
@zhuhan1236 please reset Vundle and try again(reinstall). Sorry for inconveniences…
Reopen if issues remain…

**Comment by KamranMackey** [comment]
It's not in my control anymore. you literally removed my permissions.
