### ISSUE TITLE
Bundles do not install in OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by nelson** [VundleVim/Vundle.vim#620]
Vundles uses the temporary area in `/var/folders/` during installation. In 10.11, rootless mode seems to prevent this area from being written to, *even if the user has write access to it*.

In my testing, I had to install bundles by using

```
$ sudo vim +PluginInstall +qall
```

Subsequently, you should `chown` the installed bundles back to the user, otherwise `root` will have ownership of the bundle files.

**Comment by gmarik** [comment]
I'm not quite following why did you have to use `sudo`.

Can't reproduce until have access to  El Capitan.

**Comment by nelson** [comment]
@gmarik sorry, false alarm. This has nothing to do with `sudo` or rootless mode. I ran down the wrong rabbit hole.

**Comment by gmarik** [comment]
@nelson thanks for the update!
