### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by PixelVibe** [VundleVim/Vundle.vim#622]
Hello

I am new to the vim world, and I have setup my ~/.vimrc file to use vundle as a plugin manager. 
I am using the example file from which I have commented out all the plugins, except of vundle of course which has been installed and it is working properly.
The problem now is, that I cannot install any other plugins or it seems so. For example I have added NERDTree, using " Plugin 'scrooloose/nerdtree.git' ", then I went to vim, typed ":PluginInstall" and while the information window does say that it installs my plugin in the .vim/bundle and the list of the plugins does show "> Plugin 'scrooloose/nerdtree.git'", the bundles folder is has only the vundle.vim and the plugin is not installed and/or activated.
I also checked the logs but there are no errors and it says

[2015-07-14 12:05:29] Helptags:
[2015-07-14 12:05:29] :helptags /Users/nikos/.vim/bundle/Vundle.vim/doc/
[2015-07-14 12:05:29] Helptags: 1 plugins processed

I am running on MacOS Yosemite.

EDIT: I also tried with " Plugin 'vim-scripts/L9' " and although I can see it in the plugins list it doesn't install the plugin.

**Comment by ryanoasis** [comment]
What's the output of `:PluginList` ?

Are the plugins being installed elsewhere on your system?

**Comment by PixelVibe** [comment]
@ryanoasis 

The output of :PluginList
<img width="308" alt="screen shot 2015-07-14 at 13 53 18" src="https://cloud.githubusercontent.com/assets/1628148/8672567/f80aee28-2a2f-11e5-9d72-4fb0b4367b54.png">

For :scripnames vim says that this command doesn't exist

The output of :echo &rtp is
/Users/nikos/.vim,/Users/nikos/.vim/bundle/Vundle.vim,/Users/nikos/.vim/bundle/nerdtree,/Users/nikos/.vim/bundle/L9,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfi
les/after,/Users/nikos/.vim/after,/Users/nikos/.vim/bundle/Vundle.vim,/Users/nikos/.vim/bundle/Vundle.vim/after,/Users/nikos/.vim/bundle/nerdtree/after,/Users/nikos/.vim/bundle/L9/a
fter

the paths are the correct paths, but if I list the directory
<img width="403" alt="screen shot 2015-07-14 at 13 58 16" src="https://cloud.githubusercontent.com/assets/1628148/8672602/6adc8bd2-2a30-11e5-978c-48db177e1421.png">

**Comment by ryanoasis** [comment]
Sorry for the typo, should be `scriptnames`

**Comment by PixelVibe** [comment]
:scriptnames output

<img width="516" alt="screen shot 2015-07-14 at 14 09 49" src="https://cloud.githubusercontent.com/assets/1628148/8672817/0ef2bbe6-2a32-11e5-9c7b-f3bc6a15ba3f.png">

**Comment by gmarik** [comment]
There's an option to press `l` after install finishes and see the output of the commands, please let us know what it looks like

**Comment by PixelVibe** [comment]
@gmarik the screen I have if I press "l"
<img width="592" alt="screen shot 2015-07-15 at 22 13 48" src="https://cloud.githubusercontent.com/assets/1628148/8708935/50ca8072-2b3f-11e5-899f-49d66bfdf4fc.png">

But I have also noticed the following while running the "PluginInstall"
<img width="1280" alt="screen shot 2015-07-15 at 22 15 20" src="https://cloud.githubusercontent.com/assets/1628148/8708955/71f8abfc-2b3f-11e5-9a8d-e05b3a9f064d.png">

Although at the ends it says "Done", so I am not so sure if it is related to my problem

**Comment by gmarik** [comment]
@PixelVibe oh, thanks for figuring that one out!

PS: are you running OSX El Capitan by any chance?

**Comment by PixelVibe** [comment]
@gmarik No, I run Yosemite (10.10.4)

**Comment by Bigbadboybob** [comment]
Wondering if you ever solved this. I have the exact same problem.
