### ISSUE TITLE
Add syntax highlighting to the updates file

### ISSUE THREAD

**Issue by chiphogg** [VundleVim/Vundle.vim#623]
I like to read the list of updates every time after I run `:VundleUpdate`.  Right now, it's a mass of undifferentiated white text.  But it wouldn't be very hard to make it much more readable!  Here are some ideas.

- Highlight the user name and time string at the end of every commit.
- De-emphasize all the "Merge pull request" lines.
- Set `textwidth` to zero.

**Comment by gmarik** [comment]
@chiphogg great idea!

Closing. Please open as a PR ;)

**Comment by chiphogg** [comment]
Roger. :)

It's a very busy summer for me.  If I get a chance to start working on this, I'll ping this thread.  (This is in the unlikely event that somebody else wants to take up the task before I get to it; I'd hate to block them.)

**Comment by chiphogg** [comment]
Update: I will do this.
