### ISSUE TITLE
Wrong repo URL

### ISSUE THREAD

**Issue by evanrelf** [VundleVim/Vundle.vim#625]
![screen shot 2015-07-17 at 7 06 39 pm](https://cloud.githubusercontent.com/assets/887196/8759908/fb48493a-2cb6-11e5-99be-1a2568f4d28a.png)

Should be changed to use the new organization.

**Comment by ryanoasis** [comment]
:+1: Probably a good idea just for consistency even though it redirects okay ?

**Comment by gmarik** [comment]
Done
