### ISSUE TITLE
Can't do anything in Vim while Vundle is working

### ISSUE THREAD

**Issue by mrzool** [VundleVim/Vundle.vim#626]
Not sure if bug or intended behavior, but I can't switch window nor do anything else in Vim while Vundle is in the process of upgrading or installing plugins.

The code of every input I send via keyboard gets briefly printed at cursor position before disappearing when Vundle carries on with whatever is doing. Vim just becomes unusable for the whole duration of the process, which can become quite a long time if I didn't upgrade in a while.

Any hint on how to fix this, or is this thing even fixable?

**Comment by gmarik** [comment]
Vim is single threaded, which means any operation block everything else.

Give neovim a shot, it may have something better.

As a workaround you could do install in separate Vim instance. And then just reload yours when the other one is done

**Comment by mrzool** [comment]
Thank you.
