### ISSUE TITLE
Support Neovim "Remote" Plugins

### ISSUE THREAD

**Issue by brunobeltran** [VundleVim/Vundle.vim#636]
Per Neovim's documentation, (e.g. _remote-manifest_ at https://github.com/neovim/neovim/blob/master/runtime/doc/remote_plugin.txt), neovim-style "remote" plugins will require one extra step after being dropped into the appropriate directories. 

Namely, after install/removal/update of a "remote" plugin, the user must execute the command `:UpdateRemotePlugins` (once, anywhere) to update neovim's manifest of updated plugins. 

I can probably get around to submitting a patch myself pretty soon, but if not, to ease the transition for people into neovim (without breaking anything for vim users), I think there should be a default post-install/update/clean hook of

``` vim
if has('neovim')
  UpdateRemotePlugins
endif
```

**Comment by jonhoo** [comment]
FWIW, this should now read `if has('nvim')`
