### ISSUE TITLE
Install plugins from cli, script

### ISSUE THREAD

**Issue by breerly** [VundleVim/Vundle.vim#638]
I'm trying to automate installing all of my Vundle plugins by invoking the following from a script:

```
vim +PluginInstall +qall
```

This unfortunately hangs forever.

Do we need something like what `tpm` provides?

https://github.com/tmux-plugins/tpm/tree/master/bin

**Comment by breerly** [comment]
Looks like neobundle.vim allows this: https://github.com/Shougo/neobundle.vim/tree/master/bin

**Comment by trygveu** [comment]
Hi @breerly, I just tested the command here, and it works fine for me.

- Can you give it a test run with a minimal .vimrc? 
- Where exactly does it hang forever, do you have any output to your screen? 
- And how does it behave differently from running from within Vim?

**Comment by wsdjeg** [comment]
it also works fine for me 

you can read this 
https://github.com/VundleVim/Vundle.vim/issues/642

**Comment by ryanoasis** [comment]
@breerly did you ever figure this out?

**Comment by davidlowryduda** [comment]
This also works fine for me. Unless @breerly has further opinions, I believe this issue can be closed.

**Comment by ryanoasis** [comment]
Thanks @davidlowryduda
