### ISSUE TITLE
Cannot use PluginSearch

### ISSUE THREAD

**Issue by greencopper** [VundleVim/Vundle.vim#639]
I can install, view, etc, but not search. The problem exist in both Vim and Gvim.

![vundle-shot](https://cloud.githubusercontent.com/assets/1302896/9587437/d5689032-5022-11e5-8b4e-4109679e6d35.png)

**Comment by arjunkc** [comment]
I have this issue too, it was working a few days ago, and now it has stopped.

**Comment by mmcalistair** [comment]
Same here. Worked fine two days ago.

**Comment by arjunkc** [comment]
If I were to wildly speculate, my guess would be that the github or vimscripts api has changed. The mechanism that vundle uses to run its search must have changed, since the vundle code itself was untouched.

**Comment by mmcalistair** [comment]
Not sure about that. For me it only stopped working on MacOs, my Linux setup works just fine.

**Comment by arjunkc** [comment]
Weird, it doesn't work on the my arch-linux setup. I ought to look at the code...

**Comment by gmarik** [comment]
@greencopper reproduced as well, I'll take a look when I get time…
In mean time can you execute search command second time? It worked for me…

**Comment by greencopper** [comment]
I have tried it several times, also on several different boxes, I get the same problem on each box every time.

**Comment by t3zla** [comment]
Also getting this error

**Comment by Nexion** [comment]
Me too

**Comment by Shougo** [comment]
I think your Vim is too old.
You should update your Vim.

**Comment by migore** [comment]
I got the same issue, I tried the solution in issue #599 but the problem is still happening.

**Comment by noscripter** [comment]
@migore, I update the solution and it works, please refer to it.

**Comment by migore** [comment]
@noscripter Thanks! Manually downloaded the file as suggested and it's working again.

**Comment by fatso83** [comment]
@noscripter Thanks for the tip in #599. Removing the empty file fixed the problem. From what I can understand, the error is caused by 

1. the downloading of the file failed, producing an empty file
2. trying to parse the empty file as valid json

I think that Vundle should handle this case by either simply checking the file size, or catching json parsing errors, and delete the file should they arise.

**Comment by lsumnler** [comment]
It appears that Vundle searches http://vim-scripts.org to provide a list of all available VIM scripts BUT this web site is not active. Have I missed something or is there a new web site.

**Comment by arjunkc** [comment]
This is probably the right explanation. It used to exist, but the domain
appears to have expired

**Comment by kmultani** [comment]
Yes the domain has expired. Can this be fixed?

**Comment by greencopper** [comment]
It would be really cool if it could search Github :)

**Comment by ryanoasis** [comment]
@greencopper #660

**Comment by ryanoasis** [comment]
This seems to be working now. Recommending this ticket be closed. Can I get a :+1: ?

**Comment by nfischer** [comment]
@ryanoasis I can confirm, this feature works for me

**Comment by ryanoasis** [comment]
Thanks

**Comment by transcendr** [comment]
I'm experiencing this same issue.  I notice https://vim-scraper.github.io/ is no longer working.  How do I get search to work.  I've tried the suggested solution to no avail.
