### ISSUE TITLE
Vundle suddenly producing errors on load

### ISSUE THREAD

**Issue by joshghent** [VundleVim/Vundle.vim#640]
Been googling a lot around and still getting this issue. My vim suddenly produced these errors on boot. Not sure if I am missing something obvious here but I cannot for the life of me figure it out.

I've tried uninstall vundle and reinstalling multiple times as well other fixes that I have found.

The error is below. If anyone can give me a hand I would appreciate it.

```
$ vim
Error detected while processing /Users/Josh/.vimrc:
line    6:
E492: Not an editor command: see rtp+=~/.vim/bundle/vundle.vim
line    8:
E117: Unknown function: vundle#begin
line   10:
E492: Not an editor command: Plugin 'gmarik/Vundle.vim'
line   11:
E492: Not an editor command: Plugin 'tpope/vim-rails.git'
line   12:
E492: Not an editor command: Plugin 'tpope/vim-bundler'
line   13:
E492: Not an editor command: Plugin 'tpope/vim-markdown'
line   14:
E492: Not an editor command: Plugin 'vim-ruby/vim-ruby'
line   15:
E492: Not an editor command: Plugin 'kchmck/vim-coffee-script'
line   16:
E492: Not an editor command: Plugin 'pangloss/vim-javascript'
line   17:
E492: Not an editor command: Plugin 'mileszs/ack.vim'
line   18:
E492: Not an editor command: Plugin 'mattn/emmet-vim'
line   19:
E492: Not an editor command: Plugin 'ervandew/supertab'
line   21:
E492: Not an editor command: Plugin 'bling/vim-airline'
line   24:
E492: Not an editor command: Plugin 'scrooloose/nerdtree'
line   25:
E492: Not an editor command: Plugin 'jistr/vim-nerdtree-tabs'
line   26:
E492: Not an editor command: Plugin 'scrooloose/syntastic'
line   27:
E492: Not an editor command: Plugin 'xolox/vim-misc'
line   28:
E492: Not an editor command: Plugin 'majutsushi/tagbar'
line   29:
E492: Not an editor command: Plugin 'kien/ctrlp.vim'
line   30:
E492: Not an editor command: Plugin 'vim-scripts/a.vim'
line   31:
E492: Not an editor command: Plugin 'godlygeek/tabular'
line   34:
E117: Unknown function: vundle#end
default
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
> E492: Not an editor command: see rtp+=~/.vim/bundle/vundle.vim

`:set rtp+=~/.vim/bundle/vundle.vim` is correct command.
You should check `~/.vim/bundle/vundle.vim` directory is already exists though...

**Comment by joshghent** [comment]
@Shougo Yes I can cd into that directory and the `git remote -v` is correct

**Comment by nfischer** [comment]
To expand on @Shougo's answer:

Change the line `see rtp+=~/.vim/bundle/vundle.vim` to be `set rtp+=~/.vim/bundle/Vundle.vim`. You misspelled `set` and you incorrectly capitalized `Vundle.vim` as `vundle.vim`.

Also, change the line `Plugin 'gmarik/Vundle.vim'` to be `Plugin 'VundleVim/Vundle.vim'`. The URL has been updated, so this will be slightly more efficient.

If you have any more errors, post them here below. Otherwise, happy vimming!

**Comment by joshghent** [comment]
Ok, I'm now getting a different error. That is still progress! 

Thank you @nfischer and @Shougo so far for your help.

```
$ vim
Error detected while processing /Users/Josh/.vim/bundle/Vundle.vim/autoload/vundle.vim:
line    6:
E492: Not an editor command: ^M
line    9:
E182: Invalid command name
line   10:
E492: Not an editor command: ^M
line   12:
E182: Invalid command name
line   13:
E492: Not an editor command: ^M
line   15:
E182: Invalid command name
line   16:
E492: Not an editor command: ^M
line   18:
E182: Invalid command name
line   19:
E492: Not an editor command: ^M
line   21:
E182: Invalid command name
line   22:
E492: Not an editor command: ^M
line   24:
E182: Invalid command name
line   25:
E492: Not an editor command: ^M
line   28:
E492: Not an editor command: ^M
line   36:
E492: Not an editor command: ^M
line   45:
E492: Not an editor command: ^M
line   47:
E15: Invalid expression: (has('signs'))^M
line   91:
E171: Missing :endif
Error detected while processing /Users/Josh/.vimrc:
line    8:
E117: Unknown function: vundle#begin
line   10:
E492: Not an editor command: PluginInstall! 'VundleVim/Vundle.vim'^M
line   11:
E492: Not an editor command: PluginInstall! 'tpope/vim-rails.git'^M
line   12:
E492: Not an editor command: PluginInstall! 'tpope/vim-bundler'^M
line   13:
E492: Not an editor command: PluginInstall! 'tpope/vim-markdown'^M
line   14:
E492: Not an editor command: PluginInstall! 'vim-ruby/vim-ruby'^M
line   15:
E492: Not an editor command: PluginInstall! 'kchmck/vim-coffee-script'^M
line   16:
E492: Not an editor command: PluginInstall! 'pangloss/vim-javascript'^M
line   17:
E492: Not an editor command: PluginInstall! 'mileszs/ack.vim'^M
line   18:
E492: Not an editor command: PluginInstall! 'mattn/emmet-vim'^M
line   19:
E492: Not an editor command: PluginInstall! 'ervandew/supertab'^M
line   21:
E492: Not an editor command: PluginInstall! 'bling/vim-airline'^M
line   24:
E492: Not an editor command: PluginInstall! 'scrooloose/nerdtree'^M
line   25:
E492: Not an editor command: PluginInstall! 'jistr/vim-nerdtree-tabs'^M
line   26:
E492: Not an editor command: PluginInstall! 'scrooloose/syntastic'^M
line   27:
E492: Not an editor command: PluginInstall! 'xolox/vim-misc'^M
line   28:
E492: Not an editor command: PluginInstall! 'majutsushi/tagbar'^M
line   29:
E492: Not an editor command: PluginInstall! 'kien/ctrlp.vim'^M
line   30:
E492: Not an editor command: PluginInstall! 'vim-scripts/a.vim'^M
line   31:
E492: Not an editor command: PluginInstall! 'godlygeek/tabular'^M
Error detected while processing /Users/Josh/.vim/bundle/Vundle.vim/autoload/vundle.vim:
line    6:
E492: Not an editor command: ^M
line    9:
E182: Invalid command name
line   10:
E492: Not an editor command: ^M
line   12:
E182: Invalid command name
line   13:
E492: Not an editor command: ^M
line   15:
E182: Invalid command name
line   16:
E492: Not an editor command: ^M
line   18:
E182: Invalid command name
line   19:
E492: Not an editor command: ^M
line   21:
E182: Invalid command name
line   22:
E492: Not an editor command: ^M
line   24:
E182: Invalid command name
line   25:
E492: Not an editor command: ^M
line   28:
E492: Not an editor command: ^M
line   36:
E492: Not an editor command: ^M
line   45:
E492: Not an editor command: ^M
line   47:
E15: Invalid expression: (has('signs'))^M
line   91:
E171: Missing :endif
Error detected while processing /Users/Josh/.vimrc:
line   34:
E117: Unknown function: vundle#end
default
Press ENTER or type command to continue
```

**Comment by nfischer** [comment]
Ok, awesome! `^M` is the way that vim displays a Windows/Dos-style line ending. That means you're ending your lines with `\r\n` instead of the Unix-y `\n`.

**The fix?** Try this out in your command line:

```Bash
$ dos2unix ~/.vimrc
```

How can this be avoided? I think you just edited your vimrc with a Windows-y editor. Stick with using vim to edit your vimrc file and you shouldn't have this issue again. See the linked article for further explanation (or for an alternative method of fixing the `^M` problem).

https://stackoverflow.com/questions/5843495/what-does-m-character-mean-in-vim

**Comment by nfischer** [comment]
Also, I don't think you want to have `PluginInstall!` in your vimrc. I usually run that command every now and then directly from vim. Running that at startup every time will probably just slow you down. I think you can just delete those lines.

**Comment by joshghent** [comment]
@nfischer 
Ran the dos2unix command, but it just said converted and then never did. I also tried :%s/\r\n//g but again that did not seem to work.
I only remember editing my vimrc inside of vim (or maybe nano at some point) so it's a little odd I'm having this trouble.
I don't have PluginInstall! just the standard Plugin XYZ/Plugin lines, is that the same thing?

**Comment by nfischer** [comment]
Try editing your vimrc file. Do you see lots of `^M`s at the end of some of your lines? Does `:set fileformat?` return 'dos'? If you answered 'yes' to either of these questions, you might need to double check the `dos2unix` command, since that's good enough to fix that issue for me. Or take another look at that link I posted before. The `:%s` command is different than the one you did.

Also, looking over your error messages again, it looks like your vundle install might also have dos file endings. Try this out:

```Bash
$ cd ~/.vim/bundle/Vundle.vim
$ git status
```

If it says there are changed files, your vundle install might be messed up. Try these commands (see https://stackoverflow.com/questions/11929461/how-can-i-run-dos2unix-on-an-entire-directory):

```Bash
$ cd ~/.vim/bundle/Vundle.vim
$ find . -type f -exec dos2unix {} \;
```
 
If this fixes the issue, that's awesome! If your error messages change, then we're probably one step closer to a fix.

**Comment by joshghent** [comment]
Ok the fileformat was unix and there were no changes on the vundle branch. 

The `find . -type f -exec dos2unix {} \;` command seems to have fixed it. I just get this message now (which is not an error so I'm happy :+1: ) 

```
$ vim
default
Press ENTER or type command to continue
```

**Comment by trygveu** [comment]
Hi @joshghent, it seems like the two of you have found a solution. If you're happy with this you can go ahead and close this issue, by doing `Close and comment`.

**Comment by joshghent** [comment]
Oops sorry forgot to close! :)
