### ISSUE TITLE
Need to run rake make before using it

### ISSUE THREAD

**Issue by bulllog** [VundleVim/Vundle.vim#641]
Before start using this i need to run rake make in the master folder. If its required then it should be mention in the readme.

**Comment by wsdjeg** [comment]
https://github.com/VundleVim/Vundle.vim/issues/643

**Comment by trygveu** [comment]
@bulllog Have you completed step 3 in the Quick Start? https://github.com/VundleVim/Vundle.Vim#quick-start

Can you explain the steps needed to reproduce your error?

**Comment by nfischer** [comment]
@bulllog is this safe to close now?

**Comment by gmarik** [comment]
@bulllog there's no need to run `make` as far as I remember, unless you're using a custom setup…

@trygveu @nfischer thanks for jumping in guys!
Closing…
