### ISSUE TITLE
when i install the vundle plugin after reading  the README.md,and i open the vim,it came out a problem,anyone can help me?????please

### ISSUE THREAD

**Issue by v-leonhou** [VundleVim/Vundle.vim#642]
line   10:
E492: Not an editor command: Plugin 'VundleVim/Vundle.vim'
line   15:
E492: Not an editor command: Plugin 'tpope/vim-fugitive'
line   17:
E492: Not an editor command: Plugin 'L9'
line   19:
E492: Not an editor command: Plugin 'git://git.wincent.com/command-t.git'
line   21:
E492: Not an editor command: Plugin 'file:///home/gmarik/path/to/plugin'
line   24:
E492: Not an editor command: Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
line   26:
E492: Not an editor command: Plugin 'user/L9', {'name': 'newL9'}
line   29:
E117: Unknown function: vundle#end
Press ENTER or type command to continue

**Comment by Shougo** [comment]
You should upload minimal .vimrc.
I think your rtp path is wrong.

**Comment by v-leonhou** [comment]
this is my .vimrc file


set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

**Comment by Shougo** [comment]
set rtp+=~/.vim/bundle/Vundle.vim

1. Vundle is already installed?
2. You should not use `~` for rtp.  It is not expanded automatically in Windows.

**Comment by v-leonhou** [comment]
my system is ubuntu 14.04

**Comment by v-leonhou** [comment]
not installed net  i just used the command 
$ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
and set my .vimrc file like above

**Comment by v-leonhou** [comment]
when i Launch vim and run :PluginInstall
it shows E492: Not an editor command: PluginInstall

**Comment by v-leonhou** [comment]
**This text will be italic**

**Comment by Shougo** [comment]
@v-leonhou You should read other issues.
I have read other same issues in the issue tracker.

**Comment by v-leonhou** [comment]
@Shougo OK ,anyway thank you very much for your reply

**Comment by wsdjeg** [comment]
@v-leonhou 
please use these command
```
mv .vimrc .vimrc.backup
or
rm .vimrc
rm -rf .vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
```
copy this to your .vimrc
```vim
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
filetype plugin indent on
```

**Comment by wsdjeg** [comment]
if you want to install any plugin, you can add Plugin 'pluginName' after `Plugin 'VundleVim/Vundle.vim'`

**Comment by pertrai1** [comment]
@Shougo, @wsdjeg  One thing I have gotten stuck on with this process - on Windows - is that I get this message:

`E492: Not an editor command: PluginInstall! ^M`

It looks like there is something at the end that is being added to my vimrc file that is casing this issue, I am guessing. Any thoughts on how to take care of this?

**Comment by wsdjeg** [comment]
check your file type unix or dos
dos use ^M change to new line

**Comment by ryanoasis** [comment]
Yep I would check your line endings

**Comment by pertrai1** [comment]
@ryanoasis @wsdjeg  Sorry for my ignorance on this part, how would I go about changing the line endings for this? Thank you for your help.

**Comment by wsdjeg** [comment]
may be you can try with these command

```
mv .vimrc .vimrc.backup
or
rm .vimrc
rm -rf .vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
```
copy this to your .vimrc
```vim
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
filetype plugin indent on
```
open your vimrc by vim or gvim,them insert this command
```
:set fileformat=unix
:w
```
reopen your vim try with :NeobundleInstall

**Comment by pertrai1** [comment]
@wsdjeg for some unknown reason, the vimrc is coming from /etc on this machine. Don't know if this happened when I installed cygwin, but it certainly is not coming from my home directory. This maybe getting off topic, but how do I change this to look at the _vimrc file in my home directory for this Windows machine?

Thank you,
Rob

**Comment by wsdjeg** [comment]
make sure your /etc/vim/vimrc cotains this
```vim
runtime! debian.vim
```
/usr/share/vim/vim74/debian.vim contains this
```vim
set runtimepath=~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after
```

**Comment by ryanoasis** [comment]
@v-leonhou were you able to solve this?

**Comment by moqiguzhu** [comment]
@v-leonhou same problem with you . have you solven it?

**Comment by v-leonhou** [comment]
yes maybe the format is wrong,check your config file from the first line, mine is the first line something wrong

**Comment by v-leonhou** [comment]
yes maybe the format is wrong,check your config file from the first line, mine is the first line something wrong @moqiguzhu

**Comment by moqiguzhu** [comment]
I follow wsdjeg's suggestion and solve the problem. Though I have solved it, I still have no idea what wrong with my original .vimrc file. Thanks anyway. @v-leonhou

**Comment by ryanoasis** [comment]
Closing this. Reopen if anyone involved still has issues.

**Comment by PriorA** [comment]
I am having the same problem but I am not being able to solve it by the way is indicated here.  I am installing it on Windows.

**Comment by developernaren** [comment]
The issue I had was I did not source the vimrc file. Once I did `:so %` it worked.

**Comment by livia-b** [comment]
In my case  it depended on git autocrlf setting, I had autocrlf set to true instead of input  (ubuntu) https://help.github.com/articles/dealing-with-line-endings

**Comment by ryanoasis** [comment]
@PriorA does anything mentioned by @developernaren or @livia-b help you?

**Comment by HighDensityAwesome** [comment]
@wsdjeg THIS WORKED THANK YOU!

**Comment by lstebner** [comment]
I am new to Debian and needing to source the file manually was the issue for me. I assumed a fresh terminal session would do this, but it doesn't seem to be the case. thanks @developernaren !

**Comment by psychameleon** [comment]
Thanks wsdjeg! Worked for me, but also in my case, it appeared even i was still using /bin/vi. I had to :
```
mv `which vi` /bin/vi.old
ln -s `which vim` /bin/vi

```
Works perfect now. Thanks!

**Comment by tvankith** [comment]
follow @wsdjeg 
work perfect

**Comment by wsdjeg** [comment]
@tvankith welcome

**Comment by reikdas** [comment]
This is my .vim folder - https://github.com/reikdas/.vim
OS - Manjaro

Vim comes preinstalled on Manjaro. I cloned the .vim folder onto my desktop (there are no other .vim folders on my system - I checked). 

Error log -
```
[reik@reik-pc .vim]$ vim vimrc
Error detected while processing /home/reik/.vim/vimrc:
line    6:
E117: Unknown function: vundle#begin
line   11:
E492: Not an editor command: Plugin 'VundleVim/Vundle.vim'
line   14:
E492: Not an editor command: Plugin 'vim-syntastic/syntastic'
line   15:
E492: Not an editor command: Plugin 'nvie/vim-flake8'
line   18:
E492: Not an editor command: Plugin 'xuhdev/vim-latex-live-preview'
line   20:
E492: Not an editor command: Plugin 'ntpeters/vim-better-whitespace'
line   23:
E492: Not an editor command: Plugin 'derekwyatt/vim-scala'
line   25:
E117: Unknown function: vundle#end
Press ENTER or type command to continue
```

```
:PluginInstall
E492: Not an editor command: PluginInstall
```

I tried the solutions in this thread but I already have rtp set to the ones recommended in the thread and `:set fileformat=unix` didn't work.

**Comment by dizzyplay** [comment]
In my case... I need to install vim.. i was using system vi...
