### ISSUE TITLE
New Repo?

### ISSUE THREAD

**Issue by rudrab** [VundleVim/Vundle.vim#649]
Hi,
Is this same Vundle from gmarik? or is this a fork?
My vundle still works with **Plugin "gmarik/vundle"** but confused!

**Comment by ryanoasis** [comment]
Hi. It's essentially the same, see #608 particularly: "Create an organization: VundleVim". It was transferred to that organization and redirects automatically.

"When a repository is transferred, all links to the previous location are automatically redirected to the new location."

**Comment by ryanoasis** [comment]
This should probably be added somewhere like the wiki

**Comment by gmarik** [comment]
@rudrab yes, it is. Docs should be up to date mentioning it…
