### ISSUE TITLE
getting plugin clash when trying to download a plugin

### ISSUE THREAD

**Issue by teamblubee** [VundleVim/Vundle.vim#653]
Here is my vimrc file

```bash
set nocompatible              " be iMproved, required

filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo

Plugin 'Valloric/YouCompleteMe'
Plugin 'rhysd/vim-clang-format'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` 
    " to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` 
"   to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` 
"   to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

autocmd FileType c nnoremap <buffer> <silent> <C-]> :YcmCompleter GoTo<cr>
set tabstop=4 shiftwidth=4 expandtab

colorscheme elflord
:set cc=80
:set number
:set relativenumber
:syntax on
:set encoding=utf-8
:set scrolloff=3
:set autoindent
:set showmode
:set showcmd
:set hidden
:set wildmenu
:set wildmode=list:longest
:set visualbell
:set cursorline
:set ttyfast
:set ruler
:set backspace=indent,eol,start
:set laststatus=2

"YouCompleteMe
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"



"adding space when I press enter
:nnoremap <Enter> o<ESC>
:nnoremap <S-Enter> O<ESC>

"nvim terminal emulation window commands
:tnoremap <Esc> <C-\><C-n>
:tnoremap <A-h> <C-\><C-n><C-w>h
:tnoremap <A-j> <C-\><C-n><C-w>j
:tnoremap <A-k> <C-\><C-n><C-w>k
:tnoremap <A-l> <C-\><C-n><C-w>l
:nnoremap <A-h> <C-w>h
:nnoremap <A-j> <C-w>j
:nnoremap <A-k> <C-w>k
:nnoremap <A-l> <C-w>l
```

when I run VundleInstall I get this error
![error](http://i.imgur.com/ET8yMBw.png)

I don't have that plugin listed twice in my .vimrc, what could be the problem? Is it the plugin issue?

**Comment by zeka0** [comment]
This is my vimdc, I have previously installed “ultimate vimrc” from github(you can search for it, it’s pretty good).
I think you had tried to download a plugin through an old name. Sorry dude, I can’t figure out why, so as a compensate, I have attached my vimdc for you.
Ps: try NERDTree and Taglist, they are pretty great.
> "*******Vundle Plugin*******
> set runtimepath+=~/.vim_runtime
> "Vundle Plugin settings
> set nocompatible              " be iMproved, required
> filetype off                  " required
> 
> " set the runtime path to include Vundle and initialize
> set rtp+=~/.vim/bundle/Vundle.vim
> call vundle#begin()
> " alternatively, pass a path where Vundle should install plugins
> "call vundle#begin('~/some/path/here')
> 
> " let Vundle manage Vundle, required
> Plugin 'VundleVim/Vundle.vim'
> 
> " The following are examples of different formats supported.
> " Keep Plugin commands between vundle#begin/end.
> " plugin on GitHub repo
> Plugin 'tpope/vim-fugitive'
> " plugin from http://vim-scripts.org/vim/scripts.html
> Plugin 'L9'
> " Git plugin not hosted on GitHub
> Plugin 'git://git.wincent.com/command-t.git'
> " git repos on your local machine (i.e. when working on your own plugin)
> Plugin 'file:///home/gmarik/path/to/plugin'
> " The sparkup vim script is in a subdirectory of this repo called vim.
> " Pass the path to set the runtimepath properly.
> Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
> " Avoid a name conflict with L9
> Plugin 'user/L9', {'name': 'newL9'}
> 
> " All of your Plugins must be added before the following line
> call vundle#end()            " required
> filetype plugin indent on    " required
> " To ignore plugin indent changes, instead use:
> "filetype plugin on
> "
> " Brief help
> " :PluginList       - lists configured plugins
> " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
> " :PluginSearch foo - searches for foo; append `!` to refresh local cache
> " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
> "
> " see :h vundle for more details or wiki for FAQ
> " Put your non-Plugin stuff after this line
> 
> 
> "*******Snipmate Plugin*******
> Plugin 'MarcWeber/vim-addon-mw-utils'
> Plugin 'tomtom/tlib_vim'
> Plugin 'garbas/vim-snipmate'
> 
> " Optional:
> Plugin 'honza/vim-snippets'
> 
> 
> "*******Origin Plugin*******
> source ~/.vim_runtime/vimrcs/basic.vim
> source ~/.vim_runtime/vimrcs/filetypes.vim
> source ~/.vim_runtime/vimrcs/plugins_config.vim
> source ~/.vim_runtime/vimrcs/extended.vim
> 
> try
> source ~/.vim_runtime/my_configs.vim
> catch
> endtry
> 
> let g:Snippets_dir="~/.vim/snippets/" "set Snippets_dir
> 
> syntax on "set the syntax on            
> set tabstop=4 "set the tab stop to 4    
> set shiftwidth=4 "set the shift width to 4
> set smartindent "set the indent handler 
> set nu "set line number on                               
> set ruler "let shell show the current cursor position
> set hlsearch "highlight the pattern found
> set showcmd "show the unfinished command
> set noignorecase "search will not ignore case
> set directory=/Users/mac/Documents/iVim "place all the .swap file in dir
> set autochdir "automatically change the current working directory
> 
> "set omnifunc if file is java
> if has("autocmd")
> 	autocmd Filetype java setlocal omnifunc=javacomplete#Complete
> endif
> 
> set nocp "I don't know what this is
> filetype plugin on
> "set foldenable "Enable folding
> "set foldmethod=syntax "Folding according to syntax
> 
> "taglist options
> "use :TlistToggle to toggle taglist
> let Tlist_Auto_Open=1 "Automatically open Tlist on start up
> let Tlist_Show_One_File=1 "Only display current files tags
> "let Tlist_WinWidth=40 "Set window width
> "let Tlist_WinHeight=10 "Set window height
> let Tlist_Compact_Format=1 "Reduce the number of empty lines
> let Tlist_Exit_OnlyWindow=1 "Exit if only TlistWindow is on
> let Tlist_Use_Right_Window=1 "Set taglist to appeare on the right
> let Tlist_Auto_Hightlight_Tag=1 "Enable highlight on current tag
> let Tlist_Auto_Update=1 "Enable auto update
> let Tlist_Close_On_Select=0 "Don't close when selected
> 
> "NERD tree settings
> "Use NERDTreeToggle to toggle NERDTree
> let NERDTreeChristmasTree=1 "Make more colourful
> let NERDTreeAutoCenter=1 "Center aroud the cursor
> let NERDTreeChDirMode=2 "Change CWD whenever root is changed
> let NERDTreeHighlightCursorline=1 "Highlight the current line
> let NERDTreeShowBookmarks=1 "Display the bookmarks
> let NERDTreeShowFiles=1 "Display Files
> let NERDTreeShowHidden=1 "Display the hidden files
> let NERDTreeShowLineNumbers=1 "Display line numbers for the tree
> let NERDTreeWinPos="right" "Display the window on the right
> let NERDTreeIgnore=['\~$', '\.DS_Store$', '\.localized$'] "Ignore files matching the regex

**Comment by teamblubee** [comment]
That .vimrc looks like overkill for my needs at the moment. Does that explain how to actually fix the name clash issues that I asked about?

**Comment by trygveu** [comment]
Hi @teamblubee, I don't know what your issue might be, but a possible fix could be to start fresh by deleting the contents of your '.vim/bundle/' directory, and then trying :PluginInstall again. (You will have to recompile YouCompleteMe if you do this).

If that doesn't help could you run run this to help us find the name collision? 'find ~/.vim/ -name *vim-clang-format*' If you see more than the expected entry in the bundle directory, that might be the cause of the problem.

Good luck with tracing this one out.

**Comment by teamblubee** [comment]
@trygveu thank you, that seemed to have cleared up the issue.

**Comment by trygveu** [comment]
@teamblubee Great, I'm happy to hear that. Feel free to close this issue if everything worked out for you.

**Comment by ryanoasis** [comment]
@teamblubee all good? Can this be closed? :smile:

**Comment by teamblubee** [comment]
my apologies.
