### ISSUE TITLE
How can I run plugins when I start vim?

### ISSUE THREAD

**Issue by EastskyKang** [VundleVim/Vundle.vim#654]
Hello, 

Is there any shortcut to run every plugins when I start vim? 

Thnx!

**Comment by nfischer** [comment]
If you've configured your vimrc correctly, then all you should need to do is run `:PluginInstal!` once you start up vim. This will download your plugins. Once they're downloaded (a one time operation), Vundle will automatically load them up each time you start vim.

Is that what you were referring to?

**Comment by EastskyKang** [comment]
I don't know why, but in my case, plugins are not loaded when I run vim. 

It seems plugins are installed...

**Comment by trygveu** [comment]
Can you give us an example? Which plugins have you installed, and how would you expect them to act? Many of the Vim plugins doesn't change very much from how Vim presents itself.

**Comment by nfischer** [comment]
If you want to try a plugin that makes vim look obviously different, you can try the plugin `vim-airline` (https://github.com/bling/vim-airline). To use this with Vundle, add the following lines to your `.vimrc`:

```
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'bling/vim-airline'
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
set laststatus=2     " Necessary for vim-airline
```

When vim starts, run the command `:PluginInstall!`. You should see that the status bar looks noticeably different now.

**Comment by EastskyKang** [comment]
@trygveu  Thank you for help. For instance, I included molokai color scheme Plugin in my .vimrc. I want to load it when I start vim, without any command. 

but so far, to load molokai colour scheme, I always need to input command as `colorscheme molokai`. I want to load it automatically.

**Comment by EastskyKang** [comment]
@nfischer  Thank you for suggestion, I installed it as you recommended and it works nicely. But still other plugins does not loaded automatically.

**Comment by nfischer** [comment]
Did you try adding `colorscheme molokai` to your `.vimrc` file?

**Comment by EastskyKang** [comment]
@nfischer  thank you! it works now, but how about other plugins?

**Comment by nfischer** [comment]
To me this doesn't seem like a Vundle issue, since it sounds like Vundle is loading everything in the runtime path. I would suspect that you just need little bit of configuration that's specific to your plugins, not specific to Vundle (i.e. putting `colorscheme molokai` in your `.vimrc`).

If you post a list of plugins, we may be able to help out, but you'll probably have better luck searching for help for those specific plugins (i.e. if `vim-fugitive` isn't loading for you, google something like "how to install fugitive"). Let me know which you find more helpful.

And if you get everything working for you, remember to close this issue.

**Comment by ryanoasis** [comment]
@EastskyKang yes if you could please tell which plugins or an example of one that is not loading that would help. :smile:

**Comment by EastskyKang** [comment]
@nfischer @ryanoasis Thank you for help! I didn't know that I should configure .vimrc to load plugins. and [this](http://stackoverflow.com/questions/1447334/how-do-you-add-nerdtree-to-your-vimrc) works for NERDTree.

I'm going to close the issue.

**Comment by ChanForPres** [comment]
@EastskyKang 
Hi do you have to manually enter commands to get it working?
