### ISSUE TITLE
vim startup statistics

### ISSUE THREAD

**Issue by hyiltiz** [VundleVim/Vundle.vim#655]
I have created a set of simple scripts that deal with startup timing. The raw vim log output has timing for each function call, but not for each plugins. So doing a simply statistics would be great. This is written in bash (and awk, sed, grep) along with R:ggplot2 package. It would be great if you could mention this project on the lazy-loading and optimization suggestions for your project. Would that be possible?

https://github.com/hyiltiz/vim-plugins-profile

**Comment by gmarik** [comment]
@hyiltiz pretty nice! Feel free to submit PR with docs changes you'd like to see…

**Comment by hyiltiz** [comment]
I tried finding a place where it would be proper to mention it, but neither `./doc/` nor the wiki pages talks about optimization as of now. I am thinking maybe opening a new section in the `./doc` or adding a new section in the wiki page `tips and tricks` might be good. Any preference?

**Comment by gmarik** [comment]
@hyiltiz wiki sounds like a good place to me!

**Comment by hyiltiz** [comment]
OK, I will update the wiki then.

**Comment by hyiltiz** [comment]
I updated the wiki here:
https://github.com/VundleVim/Vundle.vim/wiki/Tips-and-Tricks#startup-time-optimization

I have said more than enough stuff and some background story so that all you need to do (if you think is necessary) is simply deleting stuff rather than adding stuff.

Thanks!

**Comment by gmarik** [comment]
@hyiltiz looks good, thank you!
Think it's enough to close the issue?

**Comment by hyiltiz** [comment]
Thanks! You are so supportive!

**Comment by gmarik** [comment]
@hyiltiz you're welcome! Great job on the plugin!
