### ISSUE TITLE
Not supporting shells that do not support &&.

### ISSUE THREAD

**Issue by jiegec** [VundleVim/Vundle.vim#658]
Here is the code:
```
https://github.com/VundleVim/Vundle.vim/blob/05be0a50f4ce7f0df0b9676ceee3b812cb1e27db/autoload/vundle/scripts.vim#L87
```
It uses a '&&' in the command. However, I'm using fish, so i have to 'set shell=/bin/bash' before installing.

**Comment by gmarik** [comment]
Vundle should probably be explicit about shell…

**Comment by nfischer** [comment]
The FAQ discusses this, right? Correct me if I'm mistaken. https://github.com/VundleVim/Vundle.vim/wiki#faq4

**Comment by jiegec** [comment]
Oops. Already in FAQ.
