### ISSUE TITLE
Asks for github password when I mistype plugin name

### ISSUE THREAD

**Issue by mgedmin** [VundleVim/Vundle.vim#662]
I wanted to install python_open_module.vim the other day, so I typed `:PluginInstall python_open_module.vim`.

I got a prompt `Username for 'https://github.com':` instead of a message that such a module doesn't exist (because it's actually `:PluginInstall python_open_module` without `.vim`).

**Comment by wsdjeg** [comment]
hi the plugin show you this because it can not search it from github/vim-scripts,maybe it is exits in other people's repo ,so it want you type the usename

**Comment by gmarik** [comment]
@mgedmin it's a bit tricky to detect that state… Any ideas are welcomed!

Possible workaround: poke with `curl` for 40X before running `git clone`

**Comment by mgedmin** [comment]
It's surprisingly hard to discover how to ask git not to ask for passwords (Google failed me, git's man pages for clone/fetch also), but I discovered one way that works:

```
$ git clone https://github.com/nosuch/repo
Cloning into 'repo'...
Username for 'https://github.com': ^C

$ GIT_ASKPASS=true git clone https://github.com/nosuch/repo
Cloning into 'repo'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/nosuc/repo/'
```

GIT_ASKPASS is documented in [gitcredentials(7)](https://git-scm.com/docs/gitcredentials) and [git-config(1)](https://git-scm.com/docs/git-config).

On non-POSIX systems you'd probably have to find some other binary that exits without an error and doesn't produce any output.  Although perhaps the Git for Windows distribution ships a true.exe in its copy of Mingw?  It ships a bash, so why not true?

**Comment by wsdjeg** [comment]
i can not understande what you want!
if you want git push without type the passward,i think you should add 
```
[credential] 
helper = store
```
to ~/.gitconfig

**Comment by mgedmin** [comment]
I want `:PluginInstall something-that-does-not-exist` to tell me such a plugin doesn't exist, instead of asking for my GitHub username and password..

**Comment by gmarik** [comment]
> GIT_ASKPASS is documented in gitcredentials(7) and git-config(1).

@mgedmin great find!

You can do `let $GIT_ASKPASS='true'` in `.vimrc` and it should not ask pass anymore.

Let me know how it works for you!

**Comment by gmarik** [comment]
@mgedmin: created #667 to implement it.

Closing this issue.
