### ISSUE TITLE
Vundle doesn't seem to be sourcing other files from plugin dir upon install

### ISSUE THREAD

**Issue by kshenoy** [VundleVim/Vundle.vim#666]
Hi, I'm the author of [vim-signature](https://github.com/kshenoy/vim-signature) and this [issue](https://github.com/kshenoy/vim-signature/issues/97) was filed against me. This happens in unix too.

Upon taking a closer look it seems that this could be happening because Vundle only seems to source the main file (plugin/signature.vim) and not the other files from the plugin directory.

The minimal vimrc I used for testing is:

````
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'kshenoy/vim-signature'

call vundle#end()
filetype plugin indent on
````

Please let me know if I have identified the issue incorrectly.

Thanks

**Comment by gmarik** [comment]
@kshenoy thanks for report. I'll check it ASAP…

**Comment by kshenoy** [comment]
Hi, this is not a Vundle bug. As pointed out [here](https://github.com/kshenoy/vim-signature/issues/97#issuecomment-196406727), this behavior is not a part of vim. Sorry for the trouble.

**Comment by ryanoasis** [comment]
@kshenoy Thanks for the update and status change
