### ISSUE TITLE
Vundle is not working on Mac OS X El Capitan (10.11.1)

### ISSUE THREAD

**Issue by eiger3970** [VundleVim/Vundle.vim#668]
I try to run the plugins on Mac OS X El Capitan (10.11.1), however the plugins don't run.
I have installed Vundle in ~/.vim/bundle/Vundle.vim.
I have installed my preferred plugins in ~/.vimrc and added line:
```VimL
set rtp+=~/.vim/bundle/Vundle.vim.
```

~/.vimrc sample 1st few lines:

```VimL
set nocompatible              " be iMproved, required.
filetype off                  " required.

" set the runtime path to include Vundle and initialise.
set rtp+=~/.vim/bundle/Vundle.vim


" Keep Plugin commands between vundle#begin and vundle#end.
"----------------------------------------------------------------
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins.
"call vundle#begin('~/some/path/here')

" set the runtime path to include Vundle and initialise.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins.
"call vundle#begin('~/some/path/here')

" PluginName.                                                      Tab that shows handy info at bottom of Vim.`
```
After installing the plugins in vim with command :PluginInstall, this succeeds, however using $ vim file.xyz doesn't show any of my favourite plugin features?

I have tried $ macvim -v file.xyz, however that's a GUI and I'm happy to use Terminal, if I can have the plugin features working.

```console
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Aug 22 2015 15:38:58)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

**Comment by gmarik** [comment]
@eiger3970 please follow [guide posting an issue](https://github.com/VundleVim/Vundle.vim/blob/master/CONTRIBUTING.md#try-to-eliminate-your-vimrc)

**Comment by eiger3970** [comment]
Sorry. I edited my initial issue with the $ vim --version.

**Comment by gmarik** [comment]
Based on what you posted you have 
```VimL
" set the runtime path to include Vundle and initialise.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
```
twice in your `.vimrc` Please keep just one.

**Comment by gmarik** [comment]
Closing this issue, please feel free to post here if it's still not working.
Suspecting it's a configuration issue.

**Comment by dnylpz** [comment]
I still have the issue

Vim version output

`vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv`


~/.vimrc
` Required by Vundle
set nocompatible
filetype on
filetype off
" Required info for Vundle to work

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
call vundle#end()

filetype plugin indent on
filetype plugin on
syntax on
set number`

ll .vim/bundle
`ll ~/.vim/bundle
total 0
drwxr-xr-x  16 dnylpz  staff   544B Aug 25 00:52 Vundle.vim
drwxr-xr-x  20 dnylpz  staff   680B Aug 25 00:53 powerline`
