### ISSUE TITLE
need to input github, username

### ISSUE THREAD

**Issue by tupucenwei** [VundleVim/Vundle.vim#672]
Hello,when i install vundle, it need me input user name and the password,i input,but it failed, why?

**Comment by nfischer** [comment]
Username isn't usually required. Did you misspell any repository names? This issue often arises from that. If you can't find any misspellings, try copying your vimrc below. Also, if you use any private repositories, username *should* be required. A correct username/password should work though

**Comment by gmarik** [comment]
@tupucenwei yes, you're trying to install a nonexisting plugin.

you can disable asking password, see #667
