### ISSUE TITLE
E121: Undefined variable: VundleInstalled

### ISSUE THREAD

**Issue by InsomniaNoir** [VundleVim/Vundle.vim#673]
I've rid myself of all errors running VIM with Vundle and I cannot find an answer to this issue. I have run the update on Vundle, I have verified my `~/.vimrc` and `~/.vim/bundle` folder to make sure everything matched case sensitive.

Everytime I boot VIM I receive the following message:

```
Error detected while processing /Users/jrshafer/.vim/plugin/settings/Vundle.vim:
line   10:
E121: Undefined variable: VundleInstalled
E15: Invalid expression: VundleInstalled == 1
```

**Comment by wsdjeg** [comment]
can you try with this command
```
mv ~/.vim ~/.vim_data
mv ~/.vimrc ~/.vimrc_data
makedir -p ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cp ~/.vim/bundle/Vundle.vim/test/minirc.vim ~/.vimrc
```

**Comment by ryanoasis** [comment]
@InsomniaNoir just following up were you able to solve this?

Thanks

**Comment by ryanoasis** [comment]
As far as I can tell `VundleInstalled` is custom logic and not part of Vundle.

Doing some searching and only seeing custom `vimrc` logic for it:
http://visiomaster.blogspot.com/2014/11/auto-install-pathogen-vundle-plugin.html
https://github.com/search?q=VundleInstalled&type=Code&utf8=%E2%9C%93

Closing for now
