### ISSUE TITLE
Vim Newbie

### ISSUE THREAD

**Issue by zeraus** [VundleVim/Vundle.vim#676]
I'm pretty new to Vim, installed Vundle using *git command* but don't know how to configure **~/.vimirc**. Please help! (OSX by the way.)

**Comment by shaoguangleo** [comment]
you can refer https://github.com/VundleVim/Vundle.Vim <https://github.com/VundleVim/Vundle.Vim>.
There are details about how to configure the vimrc .

Good Luck.

**Comment by ryanoasis** [comment]
@zeraus just following up. were you able to get setup?

**Comment by ryanoasis** [comment]
Closing. Please respond if you still need help
