### ISSUE TITLE
Fail start at bundle

### ISSUE THREAD

**Issue by hanhaoxian** [VundleVim/Vundle.vim#678]
Error detected while processing /Users/hanhaoxian/.vim/bundle/Vundle.vim/autoload/vundle.vim:
line    9:
E10: \ should be followed by /, ? or &
line   12:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   21:
E10: \ should be followed by /, ? or &
line   24:
E10: \ should be followed by /, ? or &
Press ENTER or type command to continue

Ｉgot the wrong message above, I've re-git-clone and set again, I guess my .vimrc something wrong after I add the code following:

```
" get system win or *nix
if(has("win32") || has("win95") || has("win64") || has("win16"))
    let g:iswindows=1
else
    let g:iswindows=0
endif

if (g:iswindows == 0)
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
elseif (g:iswindows == 1)
	set rtp+=$VIM/vimfiles/bundle/Vundle.vim/
	let path='$VIM/vimfiles/bundle'
	call vundle#rc(path)
endif

" plugin

if (g:iswindows == 0)
	call vundle#end()
endif
```

but even though I remove the g:iswindows setting, it could not work fine also...
```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"plugin
call vundle#end()
```

**Comment by hanhaoxian** [comment]
I found my vim version is build with support python, I can't find the reason, and I use the default version.

**Comment by wsdjeg** [comment]
@hanhaoxian 
what is you os?

**Comment by hanhaoxian** [comment]
@wsdjeg mac osx, I've delete the .vim directory and re-git-clone the Vundle, it print the error the same above.

**Comment by wsdjeg** [comment]
```shell
rm -rf ~/.vim
rm ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cp ~/.vim/bundle/Vundle.vim/test/minirc.vim ~/.vimrc
```

**Comment by hanhaoxian** [comment]
@wsdjeg  I've uninstall that version and use the default instead, cause I found I don't need YCM ever. Thanks.

**Comment by zzrrxx** [comment]
@haoxianhan JFYI, by adding nocompatible in the .vimrc can fix this issue.
