### ISSUE TITLE
Bundle  'example' , Plugin 'example', I can use Bundle or Plugin, is there anything different? Thank you

### ISSUE THREAD

**Issue by inature** [VundleVim/Vundle.vim#687]
Bundle  'example' 
Plugin 'example'
 I can use Bundle or Plugin, is there anything different? Thank you

**Comment by nfischer** [comment]
Bundle is the deprecated command. Plugin is the recommended command (to get all the new features). I can't remember if there is a difference for sure, but Plugin is definitely recommended going forward.

I know Plugin works between "vundle#begin" and "vundle#end" while Bundle may or may not
