### ISSUE TITLE
PluginInstall error that seems to occur independently of vimrc

### ISSUE THREAD

**Issue by fusion809** [VundleVim/Vundle.vim#689]
Hi,

I am operating on Arch Linux 64-bit, with Vim (installed via the `gvim` package) version `7.4.1187`. Whenever I run `:PluginInstall` in Vim (even with the [minirc.vim](https://github.com/VundleVim/Vundle.vim/blob/master/test/minirc.vim) .vimrc) I get this error:
```bash
Error detected while processing function vundle#installer#new[9]..vundle#config#bundle[2]..<SNR>10_check_bundle_name:
line    8:
E713: Cannot use empty key for Dictionary
Error detected while processing function vundle#installer#new:
line   18:
E121: Undefined variable: g:vundle#bundle_dir
E116: Invalid arguments for function expand(g:vundle#bundle_dir, 1)], names +  ['Helptags'])
E116: Invalid arguments for function vundle#scripts#view
```
this error began after I installed the `spf13-vim` plugin (https://github.com/spf13/spf13-vim) via running:
`curl https://j.mp/spf13-vim3 -L -o - | sh`
after I removed the `.vimrc` this plugin gave me, replacing it with my previous `.vimrc` (which you can find [here](https://github.com/fusion809/vim/blob/master/.vimrc)) I noticed my plugins seemed to have become uninstalled so I ran `:PluginInstall` to re-installed them and received this error. Switching my `.vimrc` with the `minirc.vim` I linked earlier did not fix this problem. I have seen [this issue](https://github.com/VundleVim/Vundle.vim/issues/661) and tried the solution of deleting `~/.vim/bundle/vundle.vim`, but it made no difference. 

I have also tried uninstalling and the reinstalling gVim and it made no difference to the error at hand.

Thanks for your time,
Brenton

**Comment by ALFminecraft** [comment]
+1, have this error too

**Comment by fusion809** [comment]
Well I'll be running:

```bash
#!/usr/bin/env sh

app_dir="$HOME/.spf13-vim-3"

warn() {
    echo "$1" >&2
}

die() {
    warn "$1"
    exit 1
}

rm $HOME/.vimrc
rm $HOME/.vimrc.bundles
rm -rf $HOME/.vim

rm -rf $app_dir
```
(this script is just a slightly modified version of https://raw.githubusercontent.com/spf13/spf13-vim/3.0/uninstall.sh, modified in that `rm -rf $HOME/.vim` was used instead of `rm $HOME/.vim` as `~/.vim` is a directory) and then copying my original `.vimrc` back to `~/.vimrc` fixed this problem.
