### ISSUE TITLE
Have trouble with initial setup

### ISSUE THREAD

**Issue by nanthil** [VundleVim/Vundle.vim#704]
I know this probably isn't the right forum for this, but I don't know where else to ask. 

I have read through a number of dcouments telling me how to set up vim on windows. 

```
C:\USERS\NATHAN.ROGERS\VIMFILES
    autoload
    bundle
        Vundle.vim
            autoload
                vundle
            doc
            ftplugin
            syntax
            test
                files


```
I'm not sure why or what is happening, but none of the plugins I have in my '_vimrc' file are being loaded/installed/whatever we call it for vim. Am I forgetting a symlink somewhere? I'm beginning to get really frustrated, but I don't have a choice on my OS because work. yay.

**Comment by nfischer** [comment]
@nanthil Just to double check, did you run `:PluginInstall` inside of vim? You only need to run this command once, then close vim and reopen it. Your plugins should now work.

If that's not the case, did you remember to put all your `Plugin` commands between `call vundle#begin()` and `call vundle#end()`?

**Comment by nanthil** [comment]
Yes, but I get an error 492: Not an editor command: PluginInstall. Also, Here is a copy of the vundle section of my _vimrc

"this is from the windows install documentation, as well as the '$USERPROFILE/vimfiles/bundle'
set set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
call vundle#begin('$USERPROFILE/vimfiles/bundle/')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" plugin on GitHub repo
Plugin 'scwood/vim-hybrid'
call vundle#end()            " required

**Comment by nfischer** [comment]
You put your `bundle/` folder in the wrong place. Move it out of the autoload folder, and everything should be ok:


```
C:\USERS\NATHAN.ROGERS\VIMFILES
autoload
bundle
    Vundle.vim
        autoload
            vundle
        doc
        ftplugin
        syntax
        test
            files
```

If that fixes it, feel free to close this issue.

**Comment by nanthil** [comment]
That was an indentation error. My bundle folder is at the same level as autoload.

**Comment by nfischer** [comment]
@nanthil 

> I also tired changing $HOME to $USERPROFILE and vise versa. Nothing doing.

Did you try switching it to `~`? I'm pretty sure `rtp+=~/...` will do what you want (can't remember if the env-var works there or not). This probably won't fix it, but it's worth a shot. You could also try `vundle#begin('~/vimfiles/bundle')`.

I'm away from my Windows machine, so I can't recall exactly what I have there. [Here's my vimrc](https://github.com/nfischer/vimfiles/blob/master/vimrc), but if I recall correctly, this doesn't quite work on Windows (I vaguely remember making local changes to get everything running).

**Comment by nanthil** [comment]
Good Idea, thought it didn't change anything. Getting the same error, and no bundles are installing

**Comment by ryanoasis** [comment]
@nanthil Hmm just tested this and it is working for me (Windows 10 VM):

I basically followed https://github.com/VundleVim/Vundle.vim/wiki/Vundle-for-Windows

```
cd %USERPROFILE%
git clone https://github.com/gmarik/Vundle.vim.git %USERPROFILE%/vimfiles/bundle/Vundle.vim
gvim _vimrc
```

in my `vimrc` I set it up to what you gave for yours:
```vim
"this is from the windows install documentation, as well as the '$USERPROFILE/vimfiles/bundle'
set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
call vundle#begin('$USERPROFILE/vimfiles/bundle/')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" plugin on GitHub repo
Plugin 'scwood/vim-hybrid'
call vundle#end()            " required
```

**Directory structure:**
```
C:.
└───bundle
    ├───vim-hybrid
    │   └───colors
    └───Vundle.vim
        ├───autoload
        │   └───vundle
        ├───doc
        ├───ftplugin
        ├───syntax
        └───test
            └───files
```

* can you give the output of `:scriptnames` ?

* here is mine:
```
  1: ~\_vimrc
  2: ~\vimfiles\bundle\Vundle.vim\autoload\vundle.vim
  3: ~\vimfiles\bundle\Vundle.vim\autoload\vundle\config.vim
  4: C:\Program Files (x86)\Vim\vim74\plugin\getscriptPlugin.vim
  5: C:\Program Files (x86)\Vim\vim74\plugin\gzip.vim
  6: C:\Program Files (x86)\Vim\vim74\plugin\logiPat.vim
  7: C:\Program Files (x86)\Vim\vim74\plugin\matchparen.vim
  8: C:\Program Files (x86)\Vim\vim74\plugin\netrwPlugin.vim
  9: C:\Program Files (x86)\Vim\vim74\plugin\rrhelper.vim
 10: C:\Program Files (x86)\Vim\vim74\plugin\spellfile.vim
 11: C:\Program Files (x86)\Vim\vim74\plugin\tarPlugin.vim
 12: C:\Program Files (x86)\Vim\vim74\plugin\tohtml.vim
 13: C:\Program Files (x86)\Vim\vim74\plugin\vimballPlugin.vim
 14: C:\Program Files (x86)\Vim\vim74\plugin\zipPlugin.vim
 15: C:\Program Files (x86)\Vim\vim74\menu.vim
 16: C:\Program Files (x86)\Vim\vim74\autoload\paste.vim
 17: ~\vimfiles\bundle\Vundle.vim\autoload\vundle\installer.vim
 18: ~\vimfiles\bundle\Vundle.vim\autoload\vundle\scripts.vim
```

**Comment by nanthil** [comment]
1: /etc/vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
  7: /usr/share/vim/vim74/plugin/gzip.vim
  8: /usr/share/vim/vim74/plugin/logiPat.vim
  9: /usr/share/vim/vim74/plugin/matchparen.vim
 10: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 11: /usr/share/vim/vim74/plugin/rrhelper.vim
 12: /usr/share/vim/vim74/plugin/spellfile.vim
 13: /usr/share/vim/vim74/plugin/tarPlugin.vim
 14: /usr/share/vim/vim74/plugin/tohtml.vim
 15: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 16: /usr/share/vim/vim74/plugin/zipPlugin.vim

**Comment by nanthil** [comment]
That explains it, I'm editing my C:/Program Files/.../vim/_vimrc when I should be editing my /etc/vimrc, but why? Does anyone know how windows has an etc/ and usr/ files above my c:/ dir? I have not seen this happen before.

**Comment by ryanoasis** [comment]
@nanthil I am not using `MINGW` just windows `cmd` and `gvim`. the `/usr` etc paths suggest you are using some sort of different shell environment for windows?

**Comment by nanthil** [comment]
Just mingw

**Comment by Tset-Noitamotua** [comment]
I had the same issue with "pure" vim/gvim (not  MINGW or msys) on Windows 7. Solution was to chage this line

`set rtp+=$HOME/vimfiles/bundle/Vundle.vim/`

to that 

`set rtp+=$USERPROFILE/vimfiles/bundle/Vundle.vim/`

... makes sense cause I have no `$HOME` (or `%HOME%`)  environment variable set.
