### ISSUE TITLE
installing vundle for windows 10

### ISSUE THREAD

**Issue by ThatsVincent** [VundleVim/Vundle.vim#707]
hey,
Im trying to install vundle and everything works perfectly fine until I come to the point where I must paste something in curl.cmd . The problem is that I cannot find curl.cmd although I followed all the steps in the tutorial.

link to the tutorial: https://github.com/VundleVim/Vundle.vim/wiki/Vundle-for-Windows

sorry for the stupid question
Kind regards
Vincent

**Comment by ryanoasis** [comment]
To which directory did you install Git?

You need to actually create the `curl.cmd` file by the way

**Comment by ThatsVincent** [comment]
this was actually my problem
thank you so much

**Comment by ryanoasis** [comment]
No problem. Glad you got it

**Comment by sugan0tech** [comment]
thanks guys i too have the same problem
