### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by elreydetoda** [VundleVim/Vundle.vim#709]
Hi, I was currently trying to write a bash script file, and I ran into a problem. When I was going to type an IF statement and I would get to the end of the condition statement whenever I would hit enter to go to the next line vim would crash. 

So now you are probably wondering why I am commenting this here, so what I did is first I just opened a file without the .sh extension and I put in the code saved it with a .sh extension and then tried to do the exact same code below it and it crashed again. So I then went though my entire vimrc file and commented everything out line by line. So as I was going through nothing would work, then I commented out Vundle and my file then didn't seg fault. So that means, at least to me, is that there is something that Vundle is processing when it is trying to interpret the .sh file extension that causes a segmentation fault.

I compiled my version of vim from source on github while following the following guide :  https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source

the version for vim is Vi IMproved 7.4

then followed this guide for making it a lot more useful:
https://realpython.com/blog/python/vim-and-python-a-match-made-in-heaven/

I am running arch (antergos install just a different flavor) the following is what I get in return from uname -a (without date and hostname) : 
Linux 4.4.5-1-ARCH x86_64 GNU/Linux

also I know that guide doesn't go through the process of building getting dependencies for arch, and what I did was do a pacman -S vim (which should download all the correct packages) then just did a pacman -R vim so then it just removed only vim and none of the packages that it needed. So vim runs perfectly fine till I trying and have Vundle interpret a .sh file, so to me the only logical thing is that there is something in Vundle that is making it seg fault. Like I said because it runs perfectly fine when I comment out the Vundle lines of code in my vimrc, so if you need any more information just let me know and I will be happy to oblige! I love vundle and want to make sure that it doesn't happen to someone else in the future that is why I am submitting a bug report. Like I said let me know if there is anything else you need!

**Comment by nfischer** [comment]
@elreydetoda Hmmm... seems like a strange bug to be getting. Could you provide an example snippet that causes the crash? Also, could you provide minimal vimrcs, one that will cause the crash and one that won't? I'll see if I can reproduce on my build of vim 7.4 on Ubuntu.

**Comment by elreydetoda** [comment]
I am so sorry for not responding promptly at all! I have been crazy busy at work and haven't been able to do anything! Sorry @nfischer! Ya it is a weird bug, but let me know if there is anything else that I can do on my end to help with this!


This one causes the crash.

`
filetype off
set rtp+=/home/elrey/src/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
call vundle#end()            " required
filetype plugin indent on    " required
`

This one will not, but I took out one of the required fields, so I feel as though it vundle isn't properly being called or something (correct me if I am wrong of course!).

`
filetype off
set rtp+=/home/elrey/src/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
call vundle#end()            " required
`

**Comment by nfischer** [comment]
@elreydetoda Please only call `vundle#begin()` once, not twice

**Comment by elreydetoda** [comment]
Sorry that is what i copied over and forgot to remove it, but in my actual vimrc I have one of the vundle#begin() commented out 
![2016-06-23_629x243](https://cloud.githubusercontent.com/assets/10230166/16311542/08c9ef4c-393f-11e6-95c7-25a7f7a4e277.png)

**Comment by nfischer** [comment]
Here's the vimrc I used, and it did **not** crash vim:

```viml
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

call vundle#end()            " required
filetype plugin indent on    " required
```

Make sure you're not putting things in some weird non-vundle directory (like `~/src/`). Also, make sure you clone it using the command `git clone https://github.com/VundleVim/Vundle.vim`. `gmarik/Vundle.vim` is deprecated.

**Comment by elreydetoda** [comment]
So I set everything like how you were saying to set it, and I still got the segmentation fault. This is what it looks like after I hit enter after the if statement.

![2016-06-28_447x815](https://cloud.githubusercontent.com/assets/10230166/16436808/ff5ec61a-3d6e-11e6-9967-079efb123ad7.png)

This is the only thing that I had in the test.sh file.

![2016-06-28_202x53](https://cloud.githubusercontent.com/assets/10230166/16436816/0e265bae-3d6f-11e6-90b1-9f5f6ea202d3.png)

this is all the configuration that 

![2016-06-28_587x275](https://cloud.githubusercontent.com/assets/10230166/16436871/8af13c30-3d6f-11e6-86dd-167a4bc0a5df.png)


This is the path you said make sure everything is in, and it has been I don't know why I had it declared differently in the .vimrc

![2016-06-28_852x67](https://cloud.githubusercontent.com/assets/10230166/16436873/939ddbfe-3d6f-11e6-9e88-044c1f7b81f7.png)

So I have no idea what is wrong...maybe it is just an arch thing?

**Comment by nfischer** [comment]
@elreydetoda Just tried this out again. I observed no crash, so I think this may be a bug with vim (or perhaps a mistake during setup). I'm using Ubuntu's vim-gtk package I believe.

Also, this might be aside from the point, but that doesn't look to me like useful Bash code (I think you want `[]` instead of `()`, and `$f` instead of `f`, unless this is some different shell) :smile:

**Comment by ryanoasis** [comment]
@elreydetoda Just following up. Were you ever able to solve this or still an issue?

**Comment by davidlowryduda** [comment]
Since @elreydetoda has not responded to @ryanoasis for a year and a half, I think it's safe to say that this issue is now stale and should be closed.

**Comment by ryanoasis** [comment]
Thanks @elreydetoda

**Comment by elreydetoda** [comment]
I am so sorry I don't ever remember seeing a reply, but I actually got a new computer and haven't had an issue since. Sorry @ryanoasis
