### ISSUE TITLE
Why is it "required" to let Vundle manage itself?

### ISSUE THREAD

**Issue by n-st** [VundleVim/Vundle.vim#710]
The main ReadMe states:
```
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
```

Why exactly is this "required"? What are the potential consequences of not having that line in the `vimrc`?

I'm asking because in my case Vundle.vim is a submodule of my dotfile Git repo, so Vundle throws an error when it tries to update itself (because its local repo isn't a normal checkout of the master branch).
I'd rather just update Vundle manually and only have it update the other bundles automatically.
Looking at https://github.com/VundleVim/Vundle.vim/issues/565, it seems like `:PluginClean` might try to remove the Vundle directory when it isn't explicitly mentioned in the `vimrc`. I could live with that (I don't normally have a use for `:PluginClean` anyway), but is there anything else I should be aware of?

**Comment by nfischer** [comment]
Not totally sure how "required" this actually is. For a while I was using my own custom build of Vundle and saw no issues. By default, you won't get the help files (i.e. `:help vundle`). You can fix this with an appropriate `:helptags` command.

That's just my opinion. If that's a sufficient answer for you, feel free to close this issue.

**Comment by ryanoasis** [comment]
You are right it seems to be at least for the case of the clean command.

See the change here: https://github.com/VundleVim/Vundle.vim/commit/6af116c76fcff8a9c5ed633540eeb14f9d85bb97

Comes shortly after this issue: https://github.com/VundleVim/Vundle.vim/issues/52

**Comment by ryanoasis** [comment]
Added a FAQ to the wiki because this didn't seem to go with the index wiki page as this is not a problem as much as just a question, page here; https://github.com/VundleVim/Vundle.vim/wiki/FAQ

Closing this for now :smile:
