### ISSUE TITLE
Suddenly unable to run PluginInstall, after years without problems (Plugin '')

### ISSUE THREAD

**Issue by d4goxn** [VundleVim/Vundle.vim#711]
For the first time in a long time, I added a new plugin and ran `:PluginInstall`. I saw a couple quick errors flash by, relating to `Plugin ''`, and then got a this install summary: 

```
" Installing plugins to /home/dan/.vim/bundle
Plugin ''
Helptags
```

and the log mentioned a git clone error:

```
[2016-04-01 21:28:13] 
[2016-04-01 21:28:13] Plugin 
[2016-04-01 21:28:13] $ git clone --recursive 'https://github.com/vim-scripts/.git' '/home/dan/.vim/bundle/'
[2016-04-01 21:28:13] > fatal: destination path '/home/dan/.vim/bundle' already exists and is not an empty directory.
```

I don't have a `Plugin ''` line in my `.vimrc`. For the sake of troubleshooting, I remove all plugin / bundle install commands from my `.vimrc`, except for `Plugin 'VundleVim/Vundle.vim'`,  and removed the `.vim/bundle` directory. When I rerun `:PluginInstall`, I get the exact same result, which makes no sense, because there is no possible way that `'/home/dan/.vim/bundle'` could already exist; it was not even recreated when I reran the plugin install.

I think that the root of the problem is whatever is causing Vundle to try to install `Plugin ''`. Considering this line does not exist in my `.vimrc`, and I do not add plugin/bundle lines in any other file, can anyone think of anything else that I could check to get to the bottom of this?

**Comment by ryanoasis** [comment]
That sounds very strange. Could your vimrc maybe be sourcing another file?

I am away from any computer.

**Comment by d4goxn** [comment]
.vimrc isn't sourcing anything, just a long list of bundles and plugins. If this is only affecting me, then I might as well just reinstall Vim and the plugins that I still use. Maybe something important has changed over the past few years, that I will discover by going through setup instructions again.

I'm going to close this for now; if a reinstall doesn't sort it out, then I'll dig a little deeper and reopen this with some more useful info, like a minimal repro.

**Comment by ryanoasis** [comment]
Thanks. Keep us up to date if you can and good luck! 👍
