### ISSUE TITLE
Plugin include order?

### ISSUE THREAD

**Issue by dragonxlwang** [VundleVim/Vundle.vim#712]
I thought the order of plugins being added in .vimrc is not important, but it seems that for example, fugitive needs to be included before airline so that the later can work. (I post a issue [there](https://github.com/vim-airline/vim-airline/issues/1115) )

However, I usually organize my plugins by their functions and it would be difficult to place them according to their dependence. Is there any good way to workaround?

**Comment by nfischer** [comment]
I use both and I don't have that issue. Feel free to check my vimfiles repo (if I misunderstood, please correct me)

**Comment by dragonxlwang** [comment]
Thanks! It seems my own problem. I forked a [colorscheme](https://github.com/dragonxlwang/molokai/blob/master/plugin/molokai.vim) and in plugin file I put ``colorscheme molokai``. It seems I can't set colorscheme in plugin file? Or otherwise it would cause me some trouble?

**Comment by nfischer** [comment]
Not sure. Either way, doesn't sound like a Vundle issue specifically, more related to vim's plugin architecture. If it's resolved now, you can probably close this issue.
