### ISSUE TITLE
a question about vundle

### ISSUE THREAD

**Issue by qiuhongfeidu** [VundleVim/Vundle.vim#713]
I install vundle as vim plugin manager. After I completed the installation, the following warnings always appear when I launch vim.

Error detected while processing /home/free/.vim/bundle/newL9/plugin/l9.vim:
line   40:
E174: Command already exists: add ! to replace it
line   89:
E174: Command already exists: add ! to replace it
line  100:
E174: Command already exists: add ! to replace it
line  104:
E174: Command already exists: add ! to replace it
Press ENTER or type command to continue

I attempted to run the command of PluginInstall! in Vim. But the problem was not solved yet.
What I should do to fix it?

**Comment by ryanoasis** [comment]
can you try removing l9 from your configured plugins in your vimrc as well as the bundle source folder (newL9) ?

**Comment by qiuhongfeidu** [comment]
According to your reply, I removed ascenator/L9,  and the problem was solved. Thanks a lot!

**Comment by ryanoasis** [comment]
Thanks for the update. Glad that was it :smile:

**Comment by dibbadu** [comment]
@ryanoasis will tit create a problem if we remove L9?

**Comment by ryanoasis** [comment]
@dibbadu No it shouldn't cause any issues. It's just an example but seems to cause confusion.

I hope that I understood your question and sorry for the late response.

**Comment by sachinnaik** [comment]
After removing L9 solved my problem too.. Thanks.

**Comment by dibbadu** [comment]
@ryanoasis L9 wasn't the problem actually, the fish shell being Non-POSIX caused the problem.

**Comment by zhl3597** [comment]
Glad to see the answer...Thanks.

**Comment by tsimchev** [comment]
There are two version of L9 and the only difference between the two are some comments. So no worries if newL9 is removed all the functions will be sourced from L9.
