### ISSUE TITLE
looking for help 

### ISSUE THREAD

**Issue by bmyell** [VundleVim/Vundle.vim#714]
luna@404:~$ vim 
处理 /home/luna/.vim/bundle/newL9/plugin/l9.vim 时发生错误:
第   40 行:
E174: 命令已存在: 请加 ! 强制替换
第   89 行:
E174: 命令已存在: 请加 ! 强制替换
第  100 行:
E174: 命令已存在: 请加 ! 强制替换
第  104 行:
E174: 命令已存在: 请加 ! 强制替换
请按 ENTER 或其它命令继续

**Comment by ryanoasis** [comment]
Hey @bmyell can you please see #713 (remove l9 plugin)

**Comment by bmyell** [comment]
@ryanoasis  hello can you show the method to remove the remove l9 plugin?

**Comment by ryanoasis** [comment]
@bmyell You just need to remove this directory `/home/luna/.vim/bundle/newL9` and remove (or comment out) the `Plugin 'ascenator/L9', {'name': 'newL9'}` line in your `vimrc`

**Comment by bmyell** [comment]
@ryanoasis thank you!

**Comment by ryanoasis** [comment]
You are welcome 😄 

I'm assuming this is solved so I'm closing
