### ISSUE TITLE
plugins of vimrc missing when using ftplugin

### ISSUE THREAD

**Issue by CodingJonas** [VundleVim/Vundle.vim#715]
I created filetype specific settings in the .vim/after/ftplugin/ directory. This caused some weird behaviour every time I open those specified filetypes: Not all plugins are working. Some work, some cause the Error _117: Unknown function_. When I use :VundleInstall only Plugins in the filetype specific settings are shown. Do you know a solution? This is how my vimrc looks like (shortened):

```
syntax on
set nocompatible
filetype plugin indent on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/syntastic'
....
Plugin 'wesQ3/vim-windowswap'
call vundle#end()            " required
....
```

and this is how my filetype specific setting looks like:

```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'derekwyatt/vim-fswitch'
call vundle#end()            " required
....
```

**Comment by nfischer** [comment]
You're missing `filetype off` as per the README, right?

**Comment by CodingJonas** [comment]
I see. adding the line `filetype off` brings back all the plugins specified in my vimrc. (but makes vim not handling file types anymore...)
How can I use Vundle and file type specification together? 
I found this in the Vundle git: https://github.com/VundleVim/Vundle.vim/tree/master/ftplugin, but I don't really understand how that helps me.

**Comment by nfischer** [comment]
What `.vim` file are you talking about? [Here's how I'm using filetype stuff](https://github.com/nfischer/vimfiles/blob/master/vimrc#L103).

**Comment by CodingJonas** [comment]
In my case the cpp.vim file is safed separat from the .vimrc in the `.vim/after/ftplugin/` directory and looks as stated in my first post.

**Comment by nfischer** [comment]
Huh? Why do you have 2 `vundle#begin()` sections? You should only use one.

```
turn off filetype
source your plugins (all of them)
turn on filetype if you want it
```

**Comment by CodingJonas** [comment]
Oh thank you! I thought I would need `vundle#begin()` and `vundle#end()` each time I add Plugins to call Vundle properly. Now in my .vim files is only the simple `Plugin '...'` and it's working fine!
