### ISSUE TITLE
Plugin 'ascenator/L9', {'name': 'newL9'}

### ISSUE THREAD

**Issue by Shaco-Ma** [VundleVim/Vundle.vim#716]
I found when I bundled this, and then I open the vim, it has a wrong message in line 40, let me add '!', because the command is redefines, but I don't know how to add '!' in line 40,so can you help me?

 22 " This command has effect only if $L9_DEBUG is non-zero.
 23 " Used as follows:
 24 "   L9Assert a:i > 0
 25 " This command can't interpret script-local variables directly.
 26 "   NG: L9Assert s:a == 1
 27 "   OK: execute 'L9Assert ' . s:a . ' == 1'
 28 "
 29 if $L9_DEBUG
 30   command -nargs=* L9Assert call eval((<args>) ? 0 : s:handleFailedAssersion(<q-args>))
 31 
 32   function s:handleFailedAssersion(expr)
 33     echoerr '[L9Assert] Assersion failure: ' . a:expr
 34     if input('[L9Assert] Continue? (Y/N) ', 'Y') !=? 'Y'
 35       throw 'L9Assert ' . a:expr
 36     endif 
 37   endfunction
 38 
 39 else
 40   command -nargs=* L9Assert :
 41 endif

**Comment by ryanoasis** [comment]
This seems to be all about the L9 plugin and nothing to do with Vundle unless I am missing something?

Not sure I completely understand the question, however this might be what you are looking for:  http://vimdoc.sourceforge.net/htmldoc/map.html#:command-bang

**Comment by Shaco-Ma** [comment]
It seems nothing about Vundle, but This plugin is in Vunble's code.I sure to don't use it in Vundle,and nothing wrong message.

**Comment by ryanoasis** [comment]
It is only in the example from the readme however and you do not need to use it for Vundle.

You can remove the L9 plugin if you are not using it.

**Comment by ryanoasis** [comment]
Closing for now, since it seems to have nothing to do with Vundle. Please re-open if I misunderstood.
