### ISSUE TITLE
how to map keys after plugin loaded

### ISSUE THREAD

**Issue by dragonxlwang** [VundleVim/Vundle.vim#723]
I am having a problem with [yankring](https://github.com/vim-scripts/YankRing.vim), which changes the behavior of ``Y``, and I want to remap ``Y`` so that it copies to the end of line. However, if I do the map in my vimrc after the section of vundle plugins, it doesn't work as it appears the execution of YankRing is after the end of vimrc file.

The only way for me is to reload again the vimrc each time after entering a buffer.

Is there a way to map a key after package loaded and executed?

Thanks

**Comment by nfischer** [comment]
You could add an event to `VimEnter`:

```viml
augroup ReloadVimrc
  autocmd!
  autocmd VimEnter * source $MYVIMRC
augroup END
```

This isn't really the cleanest solution, but it should run your vimrc once when starting vim (the normal time it runs) and then a second time after plugins are loaded.

You could instead try writing your mapping in an `after/` directory, which is probably a cleaner solution:

```Viml
" Inside ~/.vim/after/plugin/remapY.vim
nnoremap Y y$
```

If either of those works for you, feel free to close this issue.

**Comment by dragonxlwang** [comment]
Thanks @nfischer , though your methods are quite general, but for yankring, it was my bad that I wasn't careful enough to check the doc thoroughly and it already addressed this issue with:

```
 function! YRRunAfterMaps()
        nnoremap Y   :<C-U>YRYankCount 'y$'<CR>
 endfunction
```

Thanks !

**Comment by nfischer** [comment]
Glad to hear they have a yet better solution :+1:
