### ISSUE TITLE
Error processing 'plugin_name' vundle

### ISSUE THREAD

**Issue by Alioukahere** [VundleVim/Vundle.vim#730]
I put these lines in my .vimrc file
`Bundle 'Shougo/unite.vim'`
`Bundle 'Shougo/vimproc.vim'`
`Bundle 'm2mdas/phpcomplete-extended'`
when I run the installation with **_:BundleInstall_**, I get errors _**Error processing 'plugin_name'**_ for all three bundle. And I don't understand. Help please !!!

**Comment by ryanoasis** [comment]
@Alioukahere Still having the issue? Do you have git installed? Can you check the permissions of the directory you are trying to install to? 

see if #273 helps you

**Comment by Alioukahere** [comment]
The #273 helped thanks @ryanoasis
