### ISSUE TITLE
Apparently valid git uri not recognized

### ISSUE THREAD

**Issue by JESii** [VundleVim/Vundle.vim#732]
I am modifying an existing plugin and working on a branch. When I try to reference the branch name in my .vimrc, I get an error message saying the plugin name is invalid:
<img width="758" alt="2016-05-28_0652_vundleerrmsg" src="https://cloud.githubusercontent.com/assets/486/15627693/d9d4381c-24a0-11e6-9006-7d179b7d6b0f.png">

However, when I test this uri in git, it says it's good:
<img width="837" alt="2016-05-28_0654_gitrefok" src="https://cloud.githubusercontent.com/assets/486/15627702/1921c85e-24a1-11e6-9387-383d65d5cb11.png">

What am I missing here?

**Comment by nfischer** [comment]
I don't think this sort of thing is supported in vundle, sorry. I recommend using the `pinned: 1` config option and updating manually if necessary. Hope this helps!

**Comment by JESii** [comment]
Well... the documentation clearly states that vundle: "...also allows the use of any URI `git` recognizes." and this is a valid git uri.
