### ISSUE TITLE
How to unInstall plugin?

### ISSUE THREAD

**Issue by kobiljonergashev** [VundleVim/Vundle.vim#733]
How can I uninstall the plugin?

**Comment by mudongliang** [comment]
Just delete the line " Plugin XXXX" and then ":PluginUpdate" in vim.

**Comment by nfischer** [comment]
Also, you should delete the corresponding directory in `~/.vim/bundle/`

**Comment by mudongliang** [comment]
@nfischer ":PluginClean" will do the clean task, without manually deleting the plugin directory.

**Comment by nfischer** [comment]
Yup! That will delete all directories that don't correspond to active bundles. Kind of dangerous to use if you don't know exactly what it does, so I wouldn't recommend it.

**Comment by mudongliang** [comment]
However, if you manually delete this plugin directory, what's the meaning of this plugin management software - Vundle.vim? I have to admit that it's a little dangerous if you don't know what's going on.

**Comment by kobiljonergashev** [comment]
Thank you all!

**Comment by jiezhao** [comment]
good

**Comment by aes42** [comment]
I'm having this problem. I saw it a while ago and I think I fixed it by reinstalling vim-go. That didn't seem to work this time. GOPATH is said correctly. This is MacVim, Vim version 8.1.

**Comment by hoffmanc** [comment]
Make sure you restart vim or `:source ~/.vimrc` after deleting the plugin but before running `:PluginClean`

**Comment by indexOutOfBound5** [comment]
Seems like the command syntax has changed (`:GBlame` and `:Gblame` not working for me anymore, but `:Git blame` is)

https://github.com/tpope/vim-fugitive/issues/2211

**Comment by hoffmanc** [comment]
Agreed
