### ISSUE TITLE
i can not remove plugin!!

### ISSUE THREAD

**Issue by boluo250** [VundleVim/Vundle.vim#734]
I have deleted the line Plugin 'scrooloose/syntastic'
Then  ":PluginUpdate" and :PluginClean"in vim.  

i open vim also have   invalid syntastic

**Comment by mudongliang** [comment]
You can check whether there are directories related syntastic in ~/.vim. If yes, it shows your command doesn't take effect; If not, I don't know either.

**Comment by ryanoasis** [comment]
@boluo250 Are you still having problems?

**Comment by boluo250** [comment]
@ryanoasis  yes.i forget delete the syntastic set in vimrc....

**Comment by nfischer** [comment]
@boluo250 Does that mean you figured out the problem? If so, would you be able to close this?

**Comment by robskrob** [comment]
@boluo250, what do you mean by the "syntastic set" in vimrc? @mudongliang what do you mean by "You can check whether there are directories related syntastic in ~/.vim"?

I apologize folks, but I am new to vim configurations. Thank you for considering my questions.
