### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by xorange** [VundleVim/Vundle.vim#736]
Hi,

I'm new to Vundle, and found it amazing with auto-downloading, updating Vim plugins.

And I'm trying to use it on one of my PC that does not have an Internet access.

(Actually all my computers at work do not have an Internet access. Sad )

So I'd downloaded Vundle and several other vim plugins that I would like to use, place under `~/.vim/bundle` and edit my `~/.vimrc` correspondingly

With cmd `:PluginInstall` in vim, I could see the Vundle windows indicating that it's actually working, trying to download plugins that I specified in .vimrc, one by one.

Since I did not have Internet access then, the git clone would never success. Though I've downloaded the plugins manually, it seemed that Vundle still would not work with them.

Is it true that Vundle doesn't have a offline support? Or did I do anything wrong?

Thank a lot!

**Comment by nfischer** [comment]
Plugin install is to do the initial install, you only run this to download **new** plugins. 

If you have all the plugins already downloaded (in the right place), you don't need to run any commands :+1:

**Comment by xorange** [comment]
Ah ha! Will try it then

Thanks!

**Comment by ryanoasis** [comment]
Vundle can also update your plugins too, but yeah if you are offline you'd have to manually update them as well

**Comment by xorange** [comment]
Plugins worked, will close issue now.

Thank you all
