### ISSUE TITLE
Error report when I use vim after updating the Pandas

### ISSUE THREAD

**Issue by gnpang** [VundleVim/Vundle.vim#748]
When I use Vim after updating Pandas to version 0.18.1, I always got this 
![image](https://cloud.githubusercontent.com/assets/11819121/17714224/1fecbf5e-63bc-11e6-9fdb-002bcff036cf.png)
After I hit Enter, everything become normal. I'm not sure what happened here

**Comment by ryanoasis** [comment]
This seems to be related to the specific plugin (and therefore python modules) you are using not Vundle itself. I am closing this.

Feel free to leave more information though for future generations as to if you ever solved or what the solution was. :stuck_out_tongue_winking_eye:
