### ISSUE TITLE
(Windows)vim the vundle#begin() with a path which i passed in  vimrc didn't work!

### ISSUE THREAD

**Issue by BinFive** [VundleVim/Vundle.vim#753]
- 

     Hi there, my problem is:  i passed a path("D:\Vim\vimfiles\plugin", ) to the vundle#begin() function in vimrc, After i input :PluginInstall,   plugins did't install in that path("D:\Vim\vimfiles\plugin"), instead plugins were installed in $HOME/.vim/bundle(which is C:/users/username/.vim/bundle). 

    I am a beginner with vim ,and i installed gvim about one month ago, at the beginning , everything worked OK(plugins did install in the directory that i set to), but all of a sudden, the problem appears, and it is really strange and upsets me.

    I googled it, but i didn't find the answer. i tried uninstall and reinstall gvim,but the problem is still there. Is there anyone have already met the problem before or know how to fix it ?  i would  really appreciate if anybody give me some help here!

**Comment by BinFive** [comment]
ok, now i  know a workaround , in the "../Vundle.vim/autoload/vundle.vim" file, line 84，“let vundle#bundle_dir = expand('$HOME/.vim/bundle', 1)”，change the path to where you want to install your plugins or add the concerning configuration in your vimrc to the vundle.vim file. But i'm still confused, why the vundle#begin() in vimrc didn't work? It worked just fine before without editing the vundle.vim file. Anybody know what's going on ?

**Comment by xietren** [comment]
Try $VIM/vimfiles/plugin/ instead of D:\Vim\vimfiles\plugin

Here is my vimrc. My vim is located in D:\Program Files (x86)\Vim\.
set rtp+=$VIM/vimfiles/bundle/Vundle.vim/
call vundle#begin('$VIM/vimfiles/bundle/')

**Comment by BinFive** [comment]
First, i'm really sorry about replying this late! In fact, i had used the form of path ($VIM/vimfiles/...) at the  beginning,it didn't work. i doubt that maybe it's the windows system's problem that i can't tell what it is. The "../Vundle.vim/autoload/vundle.vim" file seems to have priority over the vimrc. i'd been really annoyed about it,  i already quit using vundle, Although really thanks  for your reply, @xietren!
