### ISSUE TITLE
Unknown function: UltiSnips#SnippetsInCurrentScope

### ISSUE THREAD

**Issue by mdonahoe** [VundleVim/Vundle.vim#759]
I don't have UltiSnips installed, and my YouCompleteMe build has been complaining non-stop since I upgraded to master

```
"youcompleteme.py" 713L, 25662C
Error detected while processing function youcompleteme#Enable..<SNR>36_OnBufferRead:
line   17:
E117: Unknown function: UltiSnips#SnippetsInCurrentScope
Press ENTER or type command to continue

```

I have temporarily avoided this issue by commenting out the UltiSnip support in youcomplete.py

**Comment by mdonahoe** [comment]
whoops, this is the total wrong project... my mistake.

**Comment by leetschau** [comment]
@mdonahoe I have the same problem. How do you resolve this error?

**Comment by mdonahoe** [comment]
@leetschau The original thread says to update your Vim version, but I just commented out the offending a line of code in youcomplete.py
