### ISSUE TITLE
Error while processing l9 plugin

### ISSUE THREAD

**Issue by hao-lh** [VundleVim/Vundle.vim#761]
Hi there,
I encountered some issue while installing l9 plugin, and I've tried to remove the whole folder under .vim folder and reinstall it again, but this happens again.

And here is the screenshot when it failed.
![screen shot 2016-10-20 at 10 51 21 am](https://cloud.githubusercontent.com/assets/14138581/19617804/ce2e7b72-986c-11e6-87df-42611f0c9126.png)

![screen shot 2016-10-20 at 10 53 32 am](https://cloud.githubusercontent.com/assets/14138581/19617847/daa52bc0-986d-11e6-839f-3dbc7437f23d.png)

**Comment by ryanoasis** [comment]
This looks like l9 plugin is being loaded twice.

If you do not use the `l9` plugin I would suggest removing it from vundle install

Those line numbers correspond to user-defined commands: https://github.com/eparreno/vim-l9/blob/master/plugin/l9.vim
