### ISSUE TITLE
Error runnings:helptags

### ISSUE THREAD

**Issue by vitahlin** [VundleVim/Vundle.vim#768]
When I use Vundle to install YCM,it shows:
```c
Error running :helptags /Users/vitah/.vim/bundle/YouCompleteMe/doc
```

**Comment by vitahlin** [comment]
I have solved this,try like this.
[https://stackoverflow.com/questions/21080391/fresh-vim-install-vim-permission-errors-vundle-not-functional/21080650#21080650](https://stackoverflow.com/questions/21080391/fresh-vim-install-vim-permission-errors-vundle-not-functional/21080650#21080650)

**Comment by ryanoasis** [comment]
Thanks for closing and the update
