### ISSUE TITLE
.vimrc error pls help

### ISSUE THREAD

**Issue by NerdKid** [VundleVim/Vundle.vim#772]
Hello, 
I just installed vim and spf13 which is quite nice vim configuration. After i installed , to run type this command "vim" there is following errors:
line    1:
E492: Not an editor command: Skip to content
line    2:
E492: Not an editor command: This repository
line    3:
E492: Not an editor command: Search
line    4:
E492: Not an editor command: Pull requests
line    5:
E492: Not an editor command: Issues
line    6:
E492: Not an editor command: Gist
line    8:
E492: Not an editor command:  Watch 596
line    9:
E492: Not an editor command:   Star 9,333
line   10:
E492: Not an editor command:   Fork 2,853 spf13/spf13-vim
line   11:
E492: Not an editor command:  Code  Issues 269  Pull requests 21  Projects 0  Wiki  Pulse  Graphs
line   12:
E492: Not an editor command: Branch: 3.0 Find file Copy pathspf13-vim/.vimrc
line   13:
E172: Only one file name allowed: cd86dbd  on Feb 3
line   15:
E492: Not an editor command: 93 contributors @spf13 @johntyree @taxilian @sbennett18 @bloveridge @JoveYu @chrisnicola @lukedomanski @jcbwlkr @perfectworks @jamestomasino @jphustman @victoredwardocallaghan @mmikitka @parherman @teasp00n @j1mr10rd4n @wolfgangpfnuer @Gaelan @stephpy @ramonmaruko @rekendahl @SaswatPadhi @toejough @munkt0n @lihuazhang and others
line   16:
E492: Not an editor command: RawBlameHistory    
line   17:
E492: Not an editor command: 1252 lines (1090 sloc)  49.3 KB
line 1269:
E492: Not an editor command: Contact GitHub API Training Shop Blog About
line 1270:
E492: Not an editor command: © 2016 GitHub, Inc. Terms Privacy Security Status Help

my .vimrc file has a lot of datas.
Pls help guys

**Comment by jcbwlkr** [comment]
@NerdKid this is not a problem with vundle. You installed spf13 incorrectly. It looks to me like you saved the github page itself rather than install the bundle. I recommend wiping out your vimrc and starting over following the spf13 docs.

**Comment by ryanoasis** [comment]
@NerdKid Any updates?

**Comment by ryanoasis** [comment]
Closing due to long time with no response.

@NerdKid please reply/respond if you still need help.
