### ISSUE TITLE
PluginClean removes Vundle.vim

### ISSUE THREAD

**Issue by JESii** [VundleVim/Vundle.vim#773]
And then, of course, it's all broken and you have to re-install Vundle.

**Comment by willthemoor** [comment]
Same happened here.

**Comment by syossan27** [comment]
@JESii @willthemoor 
Do you write the following in .vimrc?
```
Plugin 'VundleVim/Vundle.vim'
```

**Comment by willthemoor** [comment]
Ah, no. Thank you. I still had this:

```
Plugin 'gmarik/vundle'
```

**Comment by cympfh** [comment]
`Plugin 'VundleVim/Vundle.vim'` helps to avoid to remove self, but the command looks waste.
I have put vundle.vim at `~/.vim/Vundle.vim` and added the directory to `rtp`.

**Comment by JESii** [comment]
Shoulda closed this long ago; thanks, @syossan27
