### ISSUE TITLE
:PluginInstall yields vundle#installer#new

### ISSUE THREAD

**Issue by mbilloo** [VundleVim/Vundle.vim#777]
I'm attempting to install the YouCompleteMe plugin. If I try to install the plugin using Vundle, running :PluginInstall in vim returns vundle#installer#new. I've done what @trygveu has suggested in an earlier issue (https://github.com/VundleVim/Vundle.vim/issues/635) and see that the git repository is up to date. Any suggestions?

I'm running Ubuntu Xenial (16.04) with Vim 7.4.1689.

**Comment by mbilloo** [comment]
Was able to resolve this issue by the following link:
https://alankydd.wordpress.com/2012/09/09/unknown-function-vundleinstallernew/

In summary, have the line "runtime! debian.vim" line before the vundle section not after.

**Comment by yizhikugua** [comment]
> Was able to resolve this issue by the following link:
> https://alankydd.wordpress.com/2012/09/09/unknown-function-vundleinstallernew/
> 
> In summary, have the line "runtime! debian.vim" line before the vundle section not after.

ubuntu 18.04 + vim 8.0 works well.
