### ISSUE TITLE
fatal: repository 'https://github.com/Pansenti/linux-mpu9150/' not found

### ISSUE THREAD

**Issue by shukla-ashish-92** [VundleVim/Vundle.vim#778]
I'm trying to interface MPU9150 with Raspberry pi with raspbian jessi installed on it. When I tried to fetch repositories for it, I got the following error

**Comment by Shougo** [comment]
Your repository path is wrong.
I cannot find `https://github.com/Pansenti/linux-mpu9150/` page.

**Comment by shukla-ashish-92** [comment]
I also tried  :     git clone https://github.com/Pansenti/linux-mpu9150.git and got same error. any help wpould be appreciated

**Comment by stuartblair** [comment]
I'm going to guess that since I can't get to the linux-mpu9150.git repo, but I can get to the Panseti page that the linux-mpu9150 repo is private.

**Comment by AlexisFinn** [comment]
This has nothing to do with Vundle and can not even be considered an issue (not being able to acces a private or non-existing repository is perfectly normal).
Seeing as @gmarik seems overwhelmed with issues, it would be nice to not post totally unrelated problems here.
