### ISSUE TITLE
Vundle cannot manage itself?

### ISSUE THREAD

**Issue by taq** [VundleVim/Vundle.vim#781]
Hi, after a long time using Vundle, I'm trying to create new configuration files and just faced that I don't have a line on any of my previous configuration files asking to Vundle manage Vundle, as required on the documentation. When I insert that line on my new configuration files and try to install or update plugins, I get the following message:

```
[2017-02-01 10:18:39]·                                                                     
[2017-02-01 10:18:39] Plugin VundleVim/Vundle.vim                                          |~                                                                                             
[2017-02-01 10:18:39] $ git clone --recursive 'https://github.com/VundleVim/Vundle.vim.git'|~                                                                                             
     '/home/vim/.vim/bundle/Vundle.vim'                                                        |~                                                                                             
[2017-02-01 10:18:39] > fatal: destination path '/home/vim/.vim/bundle/Vundle.vim' already |~                                                                                             
    exists and is not an empty directory. 
```
It makes sense because I already cloned Vundle, as instructed, on the `~/.vim/bundle/Vundle.vim` directory:
```
$ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
```
So Vundle won't manage itself? Is better to remove that line from the config file and update Vundle with a simple `git pull`?

**Comment by AlexisFinn** [comment]
Just move .vim/bundle/Vundle.vim somewhere else for the time being, and everything should go smoothly.
And if it's all good, get rid of old repository.

**Comment by taq** [comment]
Hey @AlexisFinn , thanks for the answer. So, it works like that: first time Vundle loads itself, then I move the directory *after* loading Vim and ask to install it again?

**Comment by AlexisFinn** [comment]
Not quite sure I understand what you're saying, but vundle should automatically reinstall everything by itself, so I would just rename your .vim directory to .vimBackup (or something) and then launch un new :PluginInstall, and everything should be back up and running with no need ot manage anything by hand.

Then either git rid of .vimBackup, or if something doesn't seem to work quite right and you can't be bothered to deal with it right now, just replace the newly created .vim with the backup and go with your original idea of updating vundle yourself.

**Comment by taq** [comment]
Ok, I'll try it, thanks. :-)
