### ISSUE TITLE
Command already exists VIM8

### ISSUE THREAD

**Issue by dotslashexec** [VundleVim/Vundle.vim#784]
After cloning the git repository to ~/.vim/bundle/Vundle.vim and then creating .vimrc at ~.vimrc and copying the config from installation instruction into the vimrc file I get "Error detected while processing /home/username/.vim/bundle/newL9/plugin/l9.vim:
Line 40:
E174: Command already exists: add ! to replace it
Line 89:
E174: Command already exists: add ! to replace it
Line 100:
E174: Command already exists: add ! to replace it
Line 104:
E174: Command already exists: add ! to replace it"
Anybody got a fix? (Using Linux ElementaryOS 64bit)

**Comment by meffect** [comment]
getting same error ubuntu

**Comment by kirkins** [comment]
Same error ^

**Comment by kirkins** [comment]
I found removing the line with:

    Plugin 'L9'

Fixed the problem, solution described here: https://github.com/VundleVim/Vundle.vim/issues/713

**Comment by ryanoasis** [comment]
Closing this. seems it is solved :smile:
