### ISSUE TITLE
Cannot execute shell /usr/bin/fish (unable to :BundleInstall)

### ISSUE THREAD

**Issue by nickdesaulniers** [VundleVim/Vundle.vim#788]
I recently [uninstalled fish shell](https://fishshell.com/docs/2.0/faq.html#faq-uninstalling) and switched back to zsh.  Unfortunately, I cannot install my Vundle Plugins:

```
Processing 'scrooloose/nerdcommenter'
Cannot execute shell /usr/bin/fish
Error detected while processing function vundle#installer#new[24]..<SNR>30_proce
ss[11]..vundle#installer#run[8]..vundle#installer#install[12]..<SNR>30_sync[11].
.<SNR>30_system:
line    1:
E484: Can't open file /tmp/v8b2exg/5
Error detected while processing function vundle#installer#new[24]..<SNR>30_proce
ss:
line   13:
E121: Undefined variable: s:last_status
E15: Invalid expression: 'error' == s:last_status
```

I think I may have:
1. installed fish and set as default shell
2. install vundle (but not plugins)
3. switched default shell
4. tried to install plugins

expected:
plugins install

actual:
an error due to trying to use a shell I no longer have installed

**Comment by AlexisFinn** [comment]
Maybe your shell is being set in vim config.
try 
`set shell?`
to see if there's a value there or 
`set all`
to print all variables.
Whether this is what's hapening or not, you can always try setting the shell in your .vimrc to override system default.
set shell=/../smyshell

**Comment by nickdesaulniers** [comment]
just went to repro this and was not able to, huh.  Thanks for your help though.

**Comment by snobb** [comment]
I suspect it's a bug in vim, cause for me this happens after some time (eg. N of shell spawns). And looks like it happens regardless of extension, etc. Some extensions make it worse though.
