### ISSUE TITLE
Plugin Setup

### ISSUE THREAD

**Issue by GoddnessTimothy** [VundleVim/Vundle.vim#789]
In your README, you provide users with a setup that requires outside plugins.  Why not just give exactly what the user needs?  Including anything extra will just make installation and setup more difficult.

**Comment by reyreaud-l** [comment]
If you refer to the Plugins listed in the 3. section, they are only examples to show how you can import plugins, and the different syntax possible. Read comments above them saying:
"The following are examples of different formats supported."
You can delete them if you don't need them.

The only one required (and is not below the comment saying they are optional) is the VundleVim plugin.

**Comment by ryanoasis** [comment]
@GoddnessTimothy Thanks, I understand where you are coming from :smile: but this is not an issue. Maybe it is not clear enough they are optional?

```vim
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
...
```
