### ISSUE TITLE
PluginUpdate on Windows 10 behinf firewall

### ISSUE THREAD

**Issue by ivostoykov** [VundleVim/Vundle.vim#790]
Hello,

I have problem updating bundles under Windows 10 behind corporate firewall. What puzzles me is that each curl and git ran separately (in command window) against github (https://github.com/VundleVim/Vundle.vim) works fine. Proxy variables and SSL/HTTPS are set and certificates as supplied. I even changed the value of $TMP/$TEMP variables just in case. Even tried set shell=git (got from some forums) but in vain.

It seems to me that curl/git fails to pass through the firewall but cannot find any log or method to register what's happened.

If I fire :PluginUpdate though it fails and I cannot fix it. Hope to get some help here.

Bellow is the output of the execution.
--- err from :PluginUpdate -----------------------
Error detected while processing function vundle#installer#new[24]..<SNR>95_process[11]..vundle#installer#run[8]..vundle#installer#install[12]..<SNR>95_sync[11]..<SNR>95_system:
line    1:
E484: Can't open file e:\PortableApps\Dev\Editors\vim\t\VIoB2EC.tmp
Error detected while processing function vundle#installer#new[24]..<SNR>95_process:
line   13:
E121: Undefined variable: s:last_status
E15: Invalid expression: 'error' == s:last_status
line   17:
E121: Undefined variable: s:last_status
E15: Invalid expression: 'updated' == s:last_status && empty(msg)
Error detected while processing function vundle#installer#new[24]..<SNR>95_process[11]..vundle#installer#run[8]..vundle#installer#install[12]..<SNR>95_sync[11]..<SNR>95_system:

--- git in command line --------------------------
f:\_\test\_>git clone https://github.com/VundleVim/Vundle.vim.git
Cloning into 'Vundle.vim'...
remote: Counting objects: 3097, done.
remote: Total 3097 (delta 0), reused 0 (delta 0), pack-reused 3097
Receiving objects: 100% (3097/3097), 922.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1087/1087), done.

--- curl in command line --------------------------
f:\_\test\_>curl -V
curl 7.53.1 (i386-pc-win32) libcurl/7.53.1 OpenSSL/1.1.0e zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.20.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy

f:\_\test\_>curl -O https://github.com/VundleVim/Vundle.vim/archive/master.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    190      0 --:--:-- --:--:-- --:--:--   190

**Comment by AlexisFinn** [comment]
That doesn't look like a connection problem to me, the message 

> E484: Can't open file e:\PortableApps\Dev\Editors\vim\t\VIoB2EC.tmp

makes me think of a permission or path problem, or maybe even a corrupted tmp file.
Have you tried moving your current plugin directory somewhere else and doing a fresh PluginInstall ?

**Comment by ivostoykov** [comment]
Yes it seemed a problem with file access. Problem gone after bunch of restarts ;-)
Thanks. Now it is working fine

**Comment by ryanoasis** [comment]
Thanks for the follow-up @ivostoykov
