### ISSUE TITLE
VundleLog

### ISSUE THREAD

**Issue by gmarik** [VundleVim/Vundle.vim#80]
by @jdevera from #69:

I reduced my config to this:

``` vim
set nocompatible
syntax on
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
filetype plugin indent on
```
## Clean - Log - Install

I ran a `BundleClean!`, then hit `l` to see the log, then ran `BundleInstall` and got this:

```
Error detected while processing function vundle#installer#clean..vundle#scripts#view:
line   11:
E21: Cannot make changes, 'modifiable' is off
```

I ran `BundleInstall` and got no error.
## Install - Log - Install

I ran `BundleInstall`, then hit `l` to see the log, then ran `BundleInstall` again:

```
Error detected while processing function vundle#installer#new..vundle#scripts#view:
line   11:
E21: Cannot make changes, 'modifiable' is off
```

Similar error, but not the same exactly.
## Install - close - Install

Another way I can repro this is by opening any file in vim, e.g., my vimrc. then run `BundleInstall` and close the installer window when it's done. Then try to run `BundleInstall` again and bang!, there it is again.

```
Error detected while processing function vundle#installer#new..vundle#scripts#view:
line   11:
E21: Cannot make changes, 'modifiable' is off
```
## List - Log - List

I run `BundleList`, then hit `l` to see the log (empty, as expected) and then run `BundleList` again, I get this:

```
Error detected while processing function vundle#installer#list..vundle#scripts#view:
line   11:
E21: Cannot make changes, 'modifiable' is off
```
## Notes

There are probably more cases, sometimes the errors disappear very quickly, I'm using the `:messages` command to see them.

**Comment by ericwoodruff** [comment]
I have to disable my dvorak remapping to get bundle install to work.

Error detected while processing function vundle#installer#new..<SNR>23_process:
line   11:
E21: Cannot make changes, 'modifiable' is off

Here's my remap:
set langmap='q,\\,w,.e,pr,yt,fy,gu,ci,ro,lp,/[,=],aa,os,ed,uf,ig,dh,hj,tk,nl,s\\;,-',\\;z,qx,jc,kv,xb,bn,mm,w\\,,v.,z/,[-,]=,\"Q,<W,>E,PR,YT,FY,GU,CI,RO,LP,?{,+},AA,OS,ED,UF,IG,DH,HJ,TK,NL,S:,_\",:Z,QX,JC,KV,XB,BN
,MM,W<,V>,Z?
