### ISSUE TITLE
 newL9  Command already exists: add ! to replace it

### ISSUE THREAD

**Issue by Mryong** [VundleVim/Vundle.vim#802]
yongpengliangdeMacBook-Pro:~ jerry.yong$ Error detected while processing /Users/yongpengliang/.vim/bundle/newL9/plugin/l9.vim:
line   40:
E174: Command already exists: add ! to replace it
line   89:
E174: Command already exists: add ! to replace it
line  100:
E174: Command already exists: add ! to replace it
line  104:
E174: Command already exists: add ! to replace it

**Comment by ryanoasis** [comment]
Please see: https://github.com/VundleVim/Vundle.vim/issues/713#issuecomment-206899770
