### ISSUE TITLE
BundleInstall fails when user name is unicode

### ISSUE THREAD

**Issue by gqqnbig** [VundleVim/Vundle.vim#813]
I'm on Windows, my username is in Unicode characters. When I run BundleInstall, it throws error "Can't open file ...."

I notice the path is not showing correctly and assume it is you or VIM that cannot process unicode path correctly.

![default](https://cloud.githubusercontent.com/assets/614159/25836604/20b4bc8c-343d-11e7-81a7-d698a3e608cc.JPG)

**Comment by ryanoasis** [comment]
@gqqnbig Wow thanks for the report :smile: . I can see if I can replicate this weekend perhaps

**Comment by gqqnbig** [comment]
I think it is system() that doesn't support Unicode path. I run
`:let a=system('ls')`

VIM gives the same error.

**Comment by ryanoasis** [comment]
Interesting, what if you:

```vim
set encoding=utf-8 
```

**Comment by gqqnbig** [comment]
I already have this. I've opened an issue in VIM.

**Comment by honggaruy** [comment]
I've had the same issue. 
But I found that this issue already fixed with [the latest VIM patch](https://github.com/vim/vim/commit/0036201a1a096913840d3df8ff08eb58eaae90a6) 
Thanks a lot~
