### ISSUE TITLE
Unknow function: vundle#installer#new

### ISSUE THREAD

**Issue by lengerrong** [VundleVim/Vundle.vim#818]
As I check via scriptnames command.
vundle.vim and vundle\config.vim are loaded.
but installer.vim and scripts.vim are not loaded.

I am using gvim.
below is my config.
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=$VIM\vimfiles\bundle\Vundle.vim\
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
filetype plugin indent on    " required

I tried push vundle config at the begining, still not work, same issue.

**Comment by ryanoasis** [comment]
@lengerrong Is this still an issue?

Sorry for the delayed response.

If so see if this is of any help: https://github.com/VundleVim/Vundle.vim/issues/635#issuecomment-140587292

**Comment by albfan** [comment]
your setup is wrong

**Comment by ryanoasis** [comment]
@albfan Wrong how?

@lengerrong Are you sure about the `rtp` path?

**Comment by lengerrong** [comment]
@ryanoasis 
sorry for the delayed response too.
thank you for your help.
the issue has already fixed.

**Comment by PICKQUE** [comment]
> @ryanoasis
> sorry for the delayed response too.
> thank you for your help.
> the issue has already fixed.

can you tell me how to fixed?
