### ISSUE TITLE
Vundle makes crontab editing error on macOS

### ISSUE THREAD

**Issue by fossilet** [VundleVim/Vundle.vim#821]
After I add Vundle config to my .vimrc, `crontab -e` returns with error:

`crontab: "/usr/bin/vi" exited with status 1`

and the file is not edited successfully.

Removing Vundle config will make crontab work again.

**Comment by albfan** [comment]
can understand how or why you run a vin inside a cron job, but vim -UNONE -unone will run it without any config

**Comment by fossilet** [comment]
`crontab -e` will invoke `vi` which is aliased to `vim`. This no longer occurs.
