### ISSUE TITLE
how to install vim plugin offline 

### ISSUE THREAD

**Issue by Kawisa** [VundleVim/Vundle.vim#823]
I have a environment that can not connect github, how i can install plugin for vim with Vundle. Thanks

**Comment by dwardu89** [comment]
You have to use some of the following commands from the README.md file. You also need to acquire the repository somehow, by transferring it on a usb stick, or getting someone else to copy it to another repository.

```
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
```

**Comment by ryanoasis** [comment]
Yes you would have to copy it to your environment with some other media (like usb drive as @dwardu89 suggested).

You would then refer to the plugin locally:
```vim
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
```
