### ISSUE TITLE
Vundle PluginInstall error: permission denied

### ISSUE THREAD

**Issue by lesterpjy** [VundleVim/Vundle.vim#833]
Here is the log after running :PluginInstall
Somehow there is some issue with the Vundle plugin. All other plugins installed just fine.
<img width="626" alt="screen shot 2017-08-27 at 11 10 44 am" src="https://user-images.githubusercontent.com/13447955/29746543-6f2f906c-8b18-11e7-9013-1dc390e30402.png">

**Comment by whitecloudy** [comment]
Did you done while using sudo command?

**Comment by pzlester** [comment]
No I just used :PluginInstall as a command line in Vim. I am still getting the same log even though the rest of the plugins installed just fine and are working perfectly in Vim.

**Comment by Karakazybra** [comment]
I got same thinks but when I tried to run vim as root(sudo vim) this error is disappeared.

**Comment by albfan** [comment]
@whitecloudy is right You cloned as sudo Vundle.vim and now you execute vim as normal user.

Output is saying it cannot write into /Users/lesteryang/.vim/bundle/Vundle.vim (for doc and updates of .git)

**Comment by hjeonE** [comment]
@Karakazybra Thank you! It worked!

**Comment by toddabraham** [comment]
> @whitecloudy is right You cloned as sudo Vundle.vim and now you execute vim as normal user.
> 
> Output is saying it cannot write into /Users/lesteryang/.vim/bundle/Vundle.vim (for doc and updates of .git)

Is there a way to solve this?

**Comment by albfan** [comment]
sudo chmod 755 -R /Users/lesteryang/.vim/bundle/Vundle.vim

**Comment by lesterpjy** [comment]
I was able to solve the issue. Thank you.
