### ISSUE TITLE
Quick Start Failure : PluginInstall

### ISSUE THREAD

**Issue by whitecloudy** [VundleVim/Vundle.vim#834]
I did what as Quick Start cause I reinstalled my Ubuntu. And I there is an error of installing 
'file:///home/gmarik/path/to/plugin'
I think this kind of file doesn't exist. Should I have to download somewhere else? Or is it the plugin don't exist anymore?

**Comment by yous** [comment]
`Plugin 'file:///home/gmarik/path/to/plugin'` is an example for git repository on your local machine. It searches `/home/gmarik/path/to/plugin` in the local machine, so you can just delete it. Feel free to delete every `Plugin` line but `Plugin 'VundleVim/Vundle.vim'`.

**Comment by whitecloudy** [comment]
Oh my god........ You're right. I was truly no better than blind..... Thank you very much.
