### ISSUE TITLE
Can't open temp files (Windows Linux Subsystem)

### ISSUE THREAD

**Issue by atsuzaki** [VundleVim/Vundle.vim#839]
Greetings,

I know this has been heavily talked about and referenced at #175, but changing the shell to /bin/bash or cmd (I inserted the System32 path) doesn't seem to work for me. Might be a WLS quirk. Would very appreciate if anyone could share their fix.

The vim I'm running is the one that came with bash on Windows 10

The vundle parts of my vimrc for now looks as the following: (should the rtp be changed to the linux configuration? it still works this way though)
```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
set shell=/bin/bash
call vundle#begin('$HOME/vimfiles/bundle/')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

call vundle#end()            " required
filetype plugin indent on    " required
```

While the error itself is as the following:
```
line    1:
E484: Can't open file /tmp/voNSud9/2
Error detected while processing function vundle#installer#new[24]..<SNR>33_process[11]..vundle#installer#run[8]..vundle#
installer#install[12]..<SNR>33_sync:
line    6:
E714: List required
Error detected while processing function vundle#installer#new[24]..<SNR>33_process:
line   13:
E121: Undefined variable: s:last_status
E15: Invalid expression: 'error' == s:last_status
line   17:
E121: Undefined variable: s:last_status
E15: Invalid expression: 'updated' == s:last_status && empty(msg)
```

**Comment by janlazo** [comment]
Output of 

```viml
set shell? shellcmdflag? shellxquote? shellxescape? shellquote? shellredir?
echom $SHELL
```

Did it break in [s:make_sync_command](https://github.com/VundleVim/Vundle.vim/blob/master/autoload/vundle/installer.vim#L380)?

**Comment by atsuzaki** [comment]
shell = cmd.exe, shellcmdflag= -c, shellxquote= , shellxescape= , shellquote= , shellredir=> , echom $SHELL=/bin/bash

it says this:
```
Error detected while processing function vundle#installer#new[24]..<SNR>29_process[11]..vundle#installer#run[8]..vundle#
installer#install[12]..<SNR>29_sync[11]..<SNR>29_system:
```

**Comment by janlazo** [comment]
In https://github.com/VundleVim/Vundle.vim/blob/master/autoload/vundle/installer.vim#L444-L449,
can you add an `echom cmd`, run Vundle, and post the value of `cmd`?

**Comment by atsuzaki** [comment]
Nope, still same error when running :PluginInstall after adding the block to my vimrc.

I added the echom just below the let cmd line, but it doesn't seem to echo anything

**Comment by janlazo** [comment]
Nothing appeared in `:messages`?

**Comment by atsuzaki** [comment]
The things that appeared in :messages were only the errors, strangely

has('unix') returned 1 and everything else were 0. echoing $TMP $TMPDIR returned empty

Here's the output of :version, https://hastebin.com/dusepunihe.rb, and uname -a in bash was `Linux DESKTOP-33AK5VQ 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by janlazo** [comment]
Thank you.
cmd.exe will not work here at so all the shell options must be set for the value of `$SHELL`.
Can you set the shell options as follows before running Vundle?
The default values for remaining shell options are assumed to be set for bash but it should be compatible with sh.

```viml
if has('unix')
  if !empty($SHELL)
    set shell=sh shellredir=>%s\ 2>&1
  endif
endif
```

**Comment by atsuzaki** [comment]
It has finally worked, thank you very much for all the help!

**Comment by Sporky023** [comment]
I was stuck here and am adding this info for anyone who find this on google.  

My situation was that setting my `shell` variable, near the top of my vimrc, wasn't fixing the issue, and the reason is that I had other code in my vimrc that was setting `shell` again, to something else.  

Here is the code which, in my case, was overriding my shell option:  https://github.com/Sporky023/dotfiles/blob/a77bac7690e3394461df3900e2cea7369f224d22/dot/vimrc#L201  

I had two options here: either disable this line of `set shell+=\ -O\ globstar`, or better, to upgrade my system's bash from version 3 to version 4 so I'd have access to the `globstar` option.
