### ISSUE TITLE
`Cannot execute shell /bin/false` on macOS

### ISSUE THREAD

**Issue by fbukevin** [VundleVim/Vundle.vim#843]
My macOS version is 10.12.6 (Sierra). And my shell is bash.

When I copied and pasted install script to .vimrc (I put it at the top of file), I got the following error:
```
Cannot execute shell /bin/false
Error detected while processing function vundle#installer#new[24]..<SNR>23_process[11]..vundle#installer#run[8]..vundle#installer#install[12]..<SNR>23_sync[11]..<SNR>23_sys
tem:
line    1:
E484: Can't open file /var/folders/0s/yp6ckctx4b1cbtzv_q31y88c37trsk/T/vmckPZT/3
Error detected while processing function vundle#installer#new[24]..<SNR>23_process:
line   13:
E121: Undefined variable: s:last_status
```

**Comment by albfan** [comment]
vundle#installer#new is called on `PluginInstall` so you have problems with that, not with .vimrc

Better post what you're trying to install

**Comment by cthulhuology** [comment]
The reason for this is by default Apple is setting the SHELL environment variable to /bin/false which does not exist.  (Correct location is /usr/bin/false).  You can fix this problem by changing your .profile file to include the correct shell:

export SHELL=$(which bash)

if you are using bash (true also by default).

This is Apple not paying attention to detail... shame on Apple.
