### ISSUE TITLE
how do i know vundle#begin() function exists?

### ISSUE THREAD

**Issue by Wsine** [VundleVim/Vundle.vim#848]
i want to let my .vimrc be this

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
if exists(':vundle#begin')
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
endif
filetype plugin indent on    " required
```

however the exists command not working. are there any other methods?

**Comment by Shougo** [comment]
`if exists(':vundle#begin')` should be `if exists('*vundle#begin')`.

But I think you should check `~/.vim/bundle/Vundle.vim` exists.

So, `if isdirectory(expand('~/.vim/bundle/Vundle.vim'))` is better.

**Comment by Wsine** [comment]
thank you very much. this helps me a lot. 

`if exists('*vundle#begin')` has no effect.

`if isdirectory(expand('~/.vim/bundle/Vundle.vim'))` works well.

**Comment by ryanoasis** [comment]
Resolved
