### ISSUE TITLE
Plugin doesn't stay installed?

### ISSUE THREAD

**Issue by HCL212** [VundleVim/Vundle.vim#861]
I added auto-pairs into my vimrc file, and did :source % while in the file, and did PluginInstall and it works fine while I'm still in the file.  Once I save and close or even open a new vim, the plugin doesn't show up on PluginList.  I can't figure out the issue here.

I also tried reinstalling vundle, deleted my whole .vim folder, reinstalled vundle and did pluginInstall, but only NERDTREE and SYNTASTIC gets installed, it completely skips over auto-pairs.

```
set nocompatible              " be iMproved, required, don't try to be Vi compatible
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/home/hughl/.vim/bundle')
" Keep Plugin commands between vundle#begin/end.

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" plugin on GitHub repo

" NERDTree (Ctrl + N to call)
Plugin 'scrooloose/nerdtree'
map <C-n> :NERDTreeToggle<CR>

" auto-pairs
Plugin 'jiangmiao/auto-pairs'

" Syntastic (Syntax Checking: SyntasticToggle)
Plugin 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_compiler_options = '-std=c++11'

" Git plugin not hosted on GitHub

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

**Comment by HCL212** [comment]
I tested it with other plugins, and it has the same behavior.  Installs correctly when I run :source % and :PluginInstall, but it gets "removed" in other vim windows.  The plugin files are still in the bundle folder, but when I do :echo &rtp, it looks like nothing is pointing to the path of the new add on?  NERDTREE and syntastic work fine though...any help?

**Comment by HCL212** [comment]
nvm I figured it out, i was editing the wrong .vimrc file

**Comment by mleroyy** [comment]
i have the same problem ! my plugin launches when i do a 'PluginInstall' and then disappear when i close the window of PluginInstall... any ideas ?

**Comment by tuchang** [comment]
> nvm I figured it out, i was editing the wrong .vimrc file

which .vimrc is the correct one?
