### ISSUE TITLE
how to change remote url from github to another?

### ISSUE THREAD

**Issue by mrlitong** [VundleVim/Vundle.vim#865]
I'm in an internal network domains.
Vundle shows me a hint like"Failed to connect to github.com port 443: Connection timed out".
So,what can I do to solve this?
(I can upload the git repo to internal gitlab)

**Comment by davidlowryduda** [comment]
You don't have any access to github from the machine?

Part of the idea of vundle is to just point to a repo and be done. If it's necessary to manually upload repositories, it seems reasonable to me that you just go ahead and manually install the plugins. (Of course that's just my opinion).

It appears that right now vundle doesn't allow pointing to generic urls. If you were inspired to modify your own vundle, then I think the place to start would be the function `parse_name` in autoload/vundle/config.vim.

**Comment by mrlitong** [comment]
it works for me,thanks,davidlowryduda.
