### ISSUE TITLE
:PluginInstall adding a `.git` to the bundle package

### ISSUE THREAD

**Issue by lucascaton** [VundleVim/Vundle.vim#878]
Hi there,

Firstly, thanks for the amazing tool - I've been using Vundle for years and love it!

I'm having problems to install the following 2 plugins:
* [msanders/snipmate.vim](https://github.com/msanders/snipmate.vim)
* [vim-scripts/matchit.zip](https://github.com/vim-scripts/matchit.zip)

When I run `:PluginInstall`, it not only adds the bundle package (to `bundle/` folder) but it also adds their `.git`, making them actuall repositories and confusing Git:

```
warning: adding embedded git repository: bundle/snipmate.vim
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: 	git submodule add <url> bundle/snipmate.vim
```

This doesn't happen with my other plugins. This is my vimfiles: https://github.com/lucascaton/vimfiles.

I've recorded a screencast in case it helps: https://d.pr/v/PUURtJ.

Am I doing anything wrong? Could you please shed some light?
Thank you very much.

**Comment by davidlowryduda** [comment]
I cannot replicate this bug. Adding for instance the line

```
Plugin 'msanders/snipmate.vim'
```

to my .vimrc and calling `:PluginInstall` installs it without any problem.

**Comment by lucascaton** [comment]
In case someone else has this issue, I solved it by switching to **vim-plug**.
