### ISSUE TITLE
"Not an editor command" from command provided by plugin executed after Plugin line

### ISSUE THREAD

**Issue by fish-face** [VundleVim/Vundle.vim#881]
I am trying to use cmdalias.vim's Alias command within my .vimrc. I place the call to Alias after all my plugins are loaded, but get the `E492: Not an editor command: Alias` error. If I run the command as soon as vim is loaded, it works.

This happens if I use a vimrc like this:
```
" Initialise vundle
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

" Set up vundle Plugins
Plugin 'gmarik/vundle'
Plugin 'vim-scripts/cmdalias.vim'

call vundle#end()

Alias

filetype on
```

Any idea what's going on?

**Comment by davidlowryduda** [comment]
I am unfamiliar with cmdalias.vim, but it appears that manually installing this plugin replicates this behavior. So I suppose this is as is intended, and this doesn't seem to concern the vundle plugin manager.

I note that https://github.com/Konfekt/vim-alias seems to be concerned with this issue and provides some additional notes on how to incorporate aliases in a vimrc (or rather in the /after config files).

Good luck.

**Comment by fish-face** [comment]
Ah sorry about that, you are correct. This doesn't seem to be documented in cmdalias but the same strategy works with that script. Thanks for your help!
