### ISSUE TITLE
missing the first character in everyfile

### ISSUE THREAD

**Issue by lihao2333** [VundleVim/Vundle.vim#886]
I have the directory with such structure
```
$tree
.
└── ABC
    ├── ABC
    │   ├── ABC
    │   │   └── a
    │   ├── abc1
    │   ├── abc2
    │   └── abc3
    ├── abc1
    ├── abc2
    └── abc3

```
However the nerdtree display is
![image](https://user-images.githubusercontent.com/33816754/49336803-fd6fbb80-f643-11e8-8f8e-d30b6595785c.png)
You can see that the first charactor is not display. 
However, when I copy it out, it's right
![image](https://user-images.githubusercontent.com/33816754/49336837-69eaba80-f644-11e8-9d6b-f1cc07fd6c38.png)
What a strange proplem. 
My environment is ubuntu14.04 with kernel3.13

**Comment by davidlowryduda** [comment]
This appears to be a problem concerning nerdtree (or some nerdtree variant), and not something concerning vundle. I suggest you raise your issue on the issue tracker for the appropriate repository.

**Comment by ryanoasis** [comment]
If this only occurs in the file directory as @davidlowryduda mentions then it seems highly unlikely it is related to Vundle. For now closing, re-open if the behavior only occurs when using Vundle.
