### ISSUE TITLE
Plugins doesn't apply

### ISSUE THREAD

**Issue by modestotech** [VundleVim/Vundle.vim#892]
I use the .vimrc file in the readme. See below: 
```
" 2018-01-08

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugin 
Plugin 'itchyny/lightline.vim'

" All of your Plugins must be added before the following line

call vundle#end()            " required
filetype plugin indent on    " required

"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
```

When I run :PluginInstall I get to the following screen: 
![image](https://user-images.githubusercontent.com/31730051/50839306-4fe97980-1360-11e9-86b2-8535ab5710d6.png)
My plugins are installed it seems. See the highlighted tabline. 

When I press :q to go back, the plugins are not applied. 
When entering vim again through the terminal, the plugins are not applied. 
![image](https://user-images.githubusercontent.com/31730051/50839371-74455600-1360-11e9-8d24-ab73d063cf4c.png)

Am I missing something?

**Comment by mwalkerwells** [comment]
+1

**Comment by mwalkerwells** [comment]
https://stackoverflow.com/questions/14114738/powerline-can-be-shown-in-multiple-buffer-but-not-in-a-single-buffer

**Comment by modestotech** [comment]
That solved it! Thanks.
