### ISSUE TITLE
Error detected while processing function <SNR>19_SetStatusLine[4]..<SNR>19_hi_statusline[2]..<SNR>19_hi:

### ISSUE THREAD

**Issue by livc** [VundleVim/Vundle.vim#894]
```bash
Error detected while processing function <SNR>19_SetStatusLine[4]..<SNR>19_hi_statusline[2]..<SNR>19_hi:
line   15:
E417: missing argument: guibg=
Press ENTER or type command to continue
E417: missing argument: guibg=
Press ENTER or type command to continue
```

I think something wrong with my vim statusline but I can't find the reason.

VIM - Vi IMproved 8.1
Ubuntu 18

Thanks.

**Comment by davidlowryduda** [comment]
This does not seem to be about vundle. Are you sure you didn't mean to raise this issue somewhere else?

**Comment by livc** [comment]
@davidlowryduda I noticed it's cauesed by a plugin https://github.com/tpope/vim-fugitive , not vundle.

**Comment by davidlowryduda** [comment]
Thanks for letting me know. Good luck!
