### ISSUE TITLE
Managing local plugins

### ISSUE THREAD

**Issue by termac** [VundleVim/Vundle.vim#9]
Vundle does not seem to handle local repositories. If e.g. I add "Bundle 'file://~/builds/vim-smart-statusline'" to vimrc and do a :BundleInstall it reports sucessfull installation but I only get an empty "file:/~/builds" directorye inside ~/.vim/bundle.

**Comment by YuMS** [comment]
I tried to build a plugin on windows, but neither `Bundle E:\somewhere\something` nor `Bundle E:/somewhere/something` nor `Bundle file://E:\somewhere\something` nor `Bundle file://E:/somewhere/something` works.

Log wrote:
```
$git clone --recursive "E:\somewhere\something" "C:\
Users\me\.vim\bundle\E:somewhere\something
fatal: could not create work tree dir 'C:\Users\me\.vim\bundle\E:somewhere\something'.: Invalid argument
```
