### ISSUE TITLE
:PluginInstall on vim 8.

### ISSUE THREAD

**Issue by Mahmoud-geberty** [VundleVim/Vundle.vim#909]
I just changed my linux distro into a newer one and 'sudo apt install vim' downloaded vim 8.

Vundle was working fine with vim 7 but now after I cloned the repo and put everything in .vimrc, running :PluginInstall yields a 'not an editor command' error. So I cloned vundle into a .vim/plugin instead of .vim/bundle and :PluginInstall finally worked but it only installed vundle plugin and completely ingnored the rest of the plugins.

**Comment by Mahmoud-geberty** [comment]
I just removed vim and  the .vim folder and reinstalled it again and everything worked.

**Comment by ryanoasis** [comment]
Thanks for follow-up. so the initial issue was incorrectly clonig into plugin folder?

Closing
