### ISSUE TITLE
A vundle problem

### ISSUE THREAD

**Issue by Dimerbone** [VundleVim/Vundle.vim#910]
error processing the command ":PluginInstall"
details:
------------------------------------------------------------------------------------------------------------------------------
running command for the first time:

Error processing function vundle#installer#new :
line 18:
E121: Undefined variables: g:vundle#bundle_dir
E116: Invalid arguments for function expand(g:vundle#bundle_dir, 1)], names +  ['Helptags'])
E116: Invalid arguments for function vundle#scripts#view
------------------------------------------------------------------------------------------------------------------------------
running command "PluginInstall" again:

Error processing function vundle#installer#new[9]..vundle#config#bundle[2]..<SNR>8_check_bundle_name:
line 2:
Vundle error: Name collision for Plugin . Plugin  previously used the name " ". Skipping Plugin .
Error processing function vundle#installer#new :
line 17:
E121: Undefined variables: name_spec
------------------------------------------------------------------------------------------------------------------------------------

**Comment by Dimerbone** [comment]
I have fixed this problem by "rm .vim/bundle/* -rf "
but I still wonder what caused this problem

**Comment by davidlowryduda** [comment]
You mention that you fixed this problem by emptying your .vim/bundle directory. Did you then re-clone vundle? And then the problem stopped?

**Comment by Dimerbone** [comment]
I didn't reclone vundle，I just deleted all vundle's config files and plugins that I installed before by vundle，then the problem disappeared.

---Original---

**Comment by ryanoasis** [comment]
It would be nice to know why it failed but since it is working for you I think it would be good house keeping to close this for now.

**Comment by charims** [comment]
I ran into this when installing vundle from the AUR where vundle already existed in my homedir. Removing vundle from my homdir .vim folder fixed it.

**Comment by yichanshiwoa** [comment]
i also meet this problem,since it occure some warning but it still work.i don't kown what happened .
