### ISSUE TITLE
Vundle doesn't work with sudo user

### ISSUE THREAD

**Issue by spiderrider** [VundleVim/Vundle.vim#933]
If I run Vundle as a non sudo user it works partly. I can install for example Nerdtree.  But if I start NERDTree I can not edit files because they all have read only status. So I start vim as root user. Then it is not possible to  communicate with Vundle. If I write :NERDTree or :PluginInstall for example I get the error message:
E492: Not an editor command: PluginInstall
What can I do?

**Comment by davidlowryduda** [comment]
There are many problems associated with running vim with sudo. The general structures of the problems are often the same --- the environment (including runtimepaths, aliases, and environmental variables) differs.

Generally I have no problem following the advice here: https://stackoverflow.com/questions/21488357/use-sudo-with-vimrc

But in fact, generally if I'm using sudo and vim, I use a minified vimrc with no plugins.

**Comment by spiderrider** [comment]
Thank you very much for the link. Now I installed everything in `root/` and it worked even with the complete vimrc.
