### ISSUE TITLE
PluginSearch fails

### ISSUE THREAD

**Issue by sheepdoggie** [VundleVim/Vundle.vim#941]
![Screenshot from 2020-08-31 12-24-58](https://user-images.githubusercontent.com/70542235/91759215-1fce9a00-eb86-11ea-8b4e-ff2f4067114c.png)

**Comment by davidlowryduda** [comment]
This is the same problem as #906. My description of the source of the problem there still applies as well.

**Comment by sheepdoggie** [comment]
Perfect! Thanks.
