### ISSUE TITLE
How to do this with Vundle?

### ISSUE THREAD

**Issue by kkoomen** [VundleVim/Vundle.vim#943]
Hi,

How can I do this vim-plug statement with Vundle?

```
Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }
```

**Comment by davidlowryduda** [comment]
Unless I'm very mistaken, this is not something that vundle can do. Vundle is rather more minimal than vim-plug (or alternately, vim-plug is rather more featureful than vundle). For complicated plugin setups, this might mean that something more than adding a single line to a .vimrc.

I chuckled at the name vim-doge by the way. It's cute.

**Comment by kkoomen** [comment]
Okay, thanks. I'll just let people call `:call doge#install()` manually.
