### ISSUE TITLE
the command is not available in this version: call vundle#begin()

### ISSUE THREAD

**Issue by zhumingyu** [VundleVim/Vundle.vim#944]
Error detected while processing /home/zjhxmjl/.vimrc:
line    6:
E319: Sorry, the command is not available in this version: call vundle#begin()
line   12:
E492: Not an editor command: Plugin 'gmarik/Vundle.vim'
line   20:
E319: Sorry, the command is not available in this version: call vundle#end()            " required
Press ENTER or type command to continue

vim version: 8.1.2269

**Comment by biaocy** [comment]
Is your `vim` a **tiny** version?
I ran into the same problem as yours, and I solved it by install the **normal** version vim.
If your `vim --version` has `Small version without GUI`, then your `vim` is tiny version.

**Comment by zhumingyu** [comment]
you're right!thx
