### ISSUE TITLE
Error in installing Plugin 'file:///home/gmarik/path/to/plugin'

### ISSUE THREAD

**Issue by kkin1995** [VundleVim/Vundle.vim#946]
The following plugin is given in the instructions in the README:
```
Plugin 'file:///home/gmarik/path/to/plugin'
```
However, when I follow the instructions to install Vundle and execute the command inside vim:
```
:PluginInstall
```
Vundle gives an error in installing it. By the looks of it, it should be a URL pointing to a custom plugin on the user's computer and therefore that line should be commented out. Any ideas?

**Comment by QuantumTarantino** [comment]
Seems an example of an installation of a custom plugin. Removing that line should be enough.

**Comment by kkin1995** [comment]
Right, I found it from the README of this repo. Should we remove it and submit a pull request ?

**Comment by jpfss** [comment]
我也被坑了
