### ISSUE TITLE
Question: How to run a command at plugin installation?

### ISSUE THREAD

**Issue by secana** [VundleVim/Vundle.vim#950]
Hi! I've got a simple question and hope you can help me.

I want to install F# plugins into vim. Unfortunately the documentation covers only vim-plug and not Vundle (which I'm using).

The installation with vim-plug looks like this:
```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'ionide/Ionide-vim', {
      \ 'do':  'make fsautocomplete',
      \}
```

How would a corresponding Vundle installation look like? I could not figure out how to do the `branch` and `do` parts of the installation.

Thx in advance!

**Comment by davidlowryduda** [comment]
Vundle doesn't have functionality for either specifying non-default branches or for running commands on installation. The closest functionality vundle provides is the ability to "pin"  a directory that you would be expected to manually clone. All the pin does is indicate to vundle that the runtimepath should include that directory.
